### ISSUE TITLE
Documentation bug for Maven/Gradle locations

### ISSUE THREAD

**Issue by rbeede** [googleapis/google-api-java-client#1008]
https://developers.google.com/api-client-library/java/apis/admin/reports_v1#add-library-to-your-project

"This library is in the process of uploading to the central Maven repository.  Please check back in a few hours."

Messages appears stuck at this stage.   Attempting to follow the See all versions available on the Maven Central Repository. link seems to go to a page with malformed search query variables since only 2014 items appear.

Looks like the Maven pom link in the documentation needs fixed.

**Comment by ejona86** [comment]
@rbeede, I see packages from January 11th, 2016 when clicking the Maven link. It does appear the "Please check back in a few hours" part is broken.

**Comment by rbeede** [comment]
I was expecting to see packages for 14 Feb 2016, but it appears the link points to older artifact id names.

I think for the report admin project the Maven needs to point to a query for

a:"google-api-services-admin-reports"

instead of google-api-services-admin

**Comment by sduskis** [comment]
This issue is obsolete.
