### ISSUE TITLE
Errors when downloading gzipped objects in chunks from GCS

### ISSUE THREAD

**Issue by mziccard** [googleapis/google-api-java-client#1009]
This issue emanates from an issue posted [here](https://github.com/GoogleCloudPlatform/gcloud-java/issues/982).

We are trying to get a gzipped GCS file in chunks. The problem comes when we try to read the response content. The problem seems to be related with the fact that [response.getContent()](https://github.com/google/google-http-java-client/blob/dev/google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java#L352) automatically creates a `GZIPInputStream` on top of the raw stream (if the content encoding is `gzip`). When we attempt to read 
the `GZIPInputStream` given by `getContent()` we get an error as that stream only holds one chunk of the original file.

Would it be possible to somehow disable the wrapping of the response content into a `GzipInputStream` when calling `getContent()`?

**Comment by Capstan** [comment]
Or have it notice there's a `Content-Range` header and disable it itself.

**Comment by mziccard** [comment]
Any updates on this?

**Comment by dalbani** [comment]
Hi, I'm very much new to this GCS library and I'm kind of surprised that this simple use case is not currently supported.
Well, a workaround has indeed been implemented AFAIK but I still fail to see how to properly handle reading a gzip-compressed blob from a `ReadChannel`, as in:
```java
ReadChannel readChannel = storage.reader(blobId);
```
How can I then determine that the data coming out this channel is actually encoded (or not) using GZIP?
Thanks for your help.

**Comment by ajaaym** [comment]
@mziccard do you expect the chunks to be of compressed bytes or non compressed bytes?

**Comment by sduskis** [comment]
I'm going to close this due to staleness.  Please open a new issue if this is still a problem.
