### ISSUE TITLE
Batch request Content-id

### ISSUE THREAD

**Issue by ashwinpatiljumia** [googleapis/google-api-java-client#1013]
Hello,
Can't we assign our own content-id in case of batch request to google api ?
I can see code snippet in BatchRequest.java as - 
```
int contentId = 1;
      for (RequestInfo<?, ?> requestInfo : requestInfos) {
        batchContent.addPart(new MultipartContent.Part(
            new HttpHeaders().setAcceptEncoding(null).set("Content-ID", contentId++),
            new HttpRequestContent(requestInfo.request)));
      }
      batchRequest.setContent(batchContent);
```

In this case, content ids of nested http-requests will always be integer. What if we want our own content ids?

Also, outer headers are not precossed in BatchUnparsedResponse.java
```
// Extract the outer headers.
    String line;
    while ((line = readLine()) != null && !line.equals("")) {
      **// Do nothing.**
    }
```

Outer header - 
`--batch_oDhHTEnhq18_AAT3kiqGBoA  ==> ignored by BatchUnparsedRequest.java
Content-Type: application/http ==> This is not processed
Content-ID: response-1`  ==> This is not processed
How can we receive default content id (assigned automatically in BatchRequest.java using contentId)

Keeping in mind, order of Batch execution in case of prediction api will not be same, how can I guarrenty output is of which input without content-id?

Thanks in advance

**Comment by sduskis** [comment]
Given the date on this question, I'm going to close it.  Please reopen it if this is still an issue.
