### ISSUE TITLE
Google Drive REST API - “modifiedDate” query field returns no results when listing children

### ISSUE THREAD

**Issue by Ionna** [googleapis/google-api-java-client#1015]
In my Java project I am using the Google Drive API in order to download files from a public Drive.
When I try to list the children of a certain folder according to some criteria everything runs as expected. Yet there is this modifiedDate field which does not return any results. No error arises, but the list is empty, despite writing a perfectly reasonable search clause (there should be quite a sum of files).

```java
Drive.Children.List firstRequest = service.children().list(folderId)
  .setQ("mimeType='application/pdf' and modifiedDate <= '2016-03-07T19:17:54.759Z'" );
do {
  ChildList result = firstRequest.execute();
  for(ChildReference child: result.getItems()) {
    File file = service.files().get(child.getId()).execute();
    System.out.printf("Found file: %s (%s): %s\n", file.getTitle(), file.getId(), file.getCreatedDate());
  }
  firstRequest.setPageToken(result.getNextPageToken());
} while (firstRequest.getPageToken() != null && firstRequest.getPageToken().length() > 0);
```

Interestingly, using the **Try It!** feature on the Google Developers' page the same query returns results as expected.

What could it be? Thank you very much!

**Comment by ajaaym** [comment]
@Ionna Is this still an issue? if yes can you please create full repro by creating some public folder and full working code?
