### ISSUE TITLE
Parsing xml element content as well as attributes with XmlObjectParser

### ISSUE THREAD

**Issue by morphine9** [googleapis/google-api-java-client#1045]
I cannot seem to parse the value out of the the following xml. What would be the parser class for parsing xml of type if I was using google-http-java client ?
```
<feed>
  <text start="1" end="10"> Text 1 </text> 
  <text start="2" end="20"> Text 2 </text> 
  <text start="3" end="30"> Text 3 </text> 
  <text start="4" end="40"> Text 4 </text> 
  <text start="5" end="50"> Text 5 </text> 
</feed>

Class Feed {
 @Key("text")
 public List<Text> textList;
}

Class Text {
  @Key("@start")
  public String startTime;


  @Key("@end")
  public String endTime; 
}
```
To be clear I want the start attribute value, end attribute value and the text content. What seems to work is the following
```
HttpRequestFactory httpRequestFactory =
        HTTP_TRANSPORT.createRequestFactory(
            new HttpRequestInitializer() {
              @Override
              public void initialize(HttpRequest request) throws IOException {
                request.setParser(new XmlObjectParser(new XmlNamespaceDictionary().set("", "")));
              }
            });

Feed feedObject = httpResponse.parseAs(Feed.class);
```
But I cannot get the content value.
If I change the feed class to the following
```
Class Feed {
     @Key("text")
     public List<String> textList;
}
```
I can only get the content and not the attribute values !
Any sample source code is very difficult to find (on github, stackoverflow etc.)

**Comment by sduskis** [comment]
@chingor13, what are your thoughts on this issue?

**Comment by chingor13** [comment]
You can specify the key as: `@Key("text()")`. See the [test example](https://github.com/googleapis/google-http-java-client/blob/fb1855551a998a1b62b319ca90840c4b45e052a4/google-http-client-xml/src/test/java/com/google/api/client/xml/GenericXmlTest.java#L347-L350) from google-http-client.
