### ISSUE TITLE
People API issue

### ISSUE THREAD

**Issue by KwonsooMoon** [googleapis/google-api-java-client#1053]
I'm using people api to retrieve user's age range and gender.
From a few days ago (I'm guessing it's after last update of people api) I'm getting 404 response for some accounts.

When user hasn't change privacy settings of his birthday and gender after account creation,
people/me api for that user gives 404 "Gender, AgeRange entity not found."
After user changes his settings, people/me api gives proper response.

test scenario:
1. create user A
2. request people/me for user A -> gives 404
3. change user A's privacy settings for birthday and gender to "Public" (I'm not sure about the term "Public" cause my language setting is Korean)
4. request people/me for user A -> gives age range and gender info
5. change user A's privacy settings for birthday and gender to "Private" 
6. request people/me for user A -> gives age range only

I think case 2 and case 6 should has same result.

**Comment by mattwhisenhunt** [comment]
"This is not the [bug tracker you are looking for](https://issuetracker.google.com/issues?q=status:open%20componentid:344199%2B%20type:bug)."

This is just a client library to connect to Google APIs. We do not have any influence over server side behavior.

**Comment by sduskis** [comment]
Alternatively, you can follow the docs at https://developers.google.com/people/ to find a link to [stackoverflow's people tag](https://stackoverflow.com/questions/tagged/google-people) and ask a question there.
