### ISSUE TITLE
siteUrl reported for Property Sets is not user friendly

### ISSUE THREAD

**Issue by liamsharp** [googleapis/google-api-java-client#1063]
If I create a Property Set, call it Foo, the `siteUrl` is some kinda of GUID, rather than Foo.

My application that uses the Java API to get a list of `siteUrl`s to display to the user then looks really bad - I list a bunch of nice looking `siteUrl`s, then the Property Sets are all `sc-set:GUID` . Here's a code snippet:

```
 public List<String> getSites()
    {
        final List<String> verifiedSites = new ArrayList<>();

        try 
        {            
            final Webmasters.Sites.List request = mWebMasters.sites().list();
            final SitesListResponse siteList = request.execute();
            final List<WmxSite> siteEntries = siteList.getSiteEntry(); 

            if (siteEntries != null)
            {
                for (WmxSite currentSite : siteEntries) 
                {
                    final String permissionLevel = currentSite.getPermissionLevel();
                    if (!"siteUnverifiedUser".equals(permissionLevel))
                    {
                        verifiedSites.add(currentSite.getSiteUrl());
                    }
                }
            }
        } 
        catch (IOException e) 
        {
            LOGGER.warn("Failed to get verified sites " + e, e);
        }
        Collections.sort(verifiedSites);
        return verifiedSites;
    }

```

**Comment by liamsharp** [comment]
No solution till Google fix their end.

**Comment by liamsharp** [comment]
Is this something that might be improved in a future release?

**Comment by jadekler** [comment]
Hey @liamsharp - sorry for the slow replies. We're fairly low on staff at the moment, and going through  some release-process fixes that will help make releases easier and more frequent in the future. Once we're done with the process fixes we'll circle back around and take a look at these issues. Apologies again for the wait.

**Comment by sduskis** [comment]
@jadekler, is this something we should look at?

**Comment by jadekler** [comment]
I don't manage these libraries anymore. Rerouting to @chingor13 and @JesseLovelace.

**Comment by sduskis** [comment]
@ajaaym, this issue, and this repo are another place where your team can add value.

**Comment by ajaaym** [comment]
@sduskis sure, will look at this.

**Comment by kamyag** [comment]
@liamsharp Is it still a problem? I can not reproduce
Can you add a code that you use for Property Set and siteUrl?

**Comment by liamsharp** [comment]
@kamyag The code to reproduce this is in my opening comment to this issue.

The key thing you need to do is (and I did this using the old GSC UI as I couldn't find it in the new one) is to create a property set in GSC:

<img width="1247" alt="screen shot 2019-01-30 at 15 41 31" src="https://user-images.githubusercontent.com/6429288/51992927-cbdd6a00-24a5-11e9-9b12-4babfa694451.png">

Although I've called this property set: "My Test set", the above code returns:

    sc-set:gig--tefyYWaaQUlFn48xw

I think it should return "My Test set"

**Comment by liamsharp** [comment]
I've just got an email from Google with the title:

"Property sets no longer supported in Search Console after March 2019"

So I guess we can close this one off!
