### ISSUE TITLE
CloudMachineLearningEngine.Projects.Predict Incorrect HTTP Body

### ISSUE THREAD

**Issue by edparris** [googleapis/google-api-java-client#1075]
The implementation of CloudMachineLearningEngine.Projects.Predict forces the use of classes 
that result in an incompatible HTTP Body being generated for the prediction request.

CloudMachineLearningEngine.Projects.Predict requires an instance of 
GoogleCloudMlV1PredictRequest on construction and GoogleCloudMlV1PredictRequest requires 
GoogleApiHttpBody. Unfortunately the JSON encoding of that class does not match the required 
input format for the API. According to spec, [GCP ML Engine V1 Predict](https://cloud.google.com/ml-engine/reference/rest/v1/projects/predict), the request should look something like this:

```javascript
{"instances": [{"b64": "9j/4AA..."}]}
```

Instead the GoogleApiHttpBody class is encoded as a wrapper around the request body that is not 
compatible with the CloudML engine prediction API:

```javascript
{
  "httpBody" : {
    "contentType" : "application/json",
    "data" : "{\"instances\": [{\"b64\": \"9j/4AA...\"}]}"
  }
}
```

```java
    String requestBody = "{\"instances\": [{\"b64\": \"9j/4AA...\"}]}";

    GoogleApiHttpBody googleApiHttpBody = new GoogleApiHttpBody();
    googleApiHttpBody.setData(requestBody);
    googleApiHttpBody.setContentType("application/json");
    GoogleCloudMlV1PredictRequest predictRequest = new GoogleCloudMlV1PredictRequest();
    predictRequest.setHttpBody(googleApiHttpBody);
    
```

This problem is also present in the .NET client library as noted in issue [#1068](https://github.com/google/google-api-dotnet-client/issues/1068)

**Comment by ajaaym** [comment]
@edparris can you please try below? 

```
    GoogleCloudMlV1PredictRequest predictRequest = new GoogleCloudMlV1PredictRequest();
    predictRequest.set("instances",<Array or what ever data you want to pass for instnaces>});
```

GoogleApiHttpBody should only be used for non json data.

**Comment by ajaaym** [comment]
closing this for now. Please feel free to reopen with more information if needed.
