### ISSUE TITLE
How can I hide the client_secret for open source project

### ISSUE THREAD

**Issue by jackyq2015** [googleapis/google-api-java-client#1100]
For an open source project, is there any way that I can hide the CLIENT_SECRET:
```
AuthorizationCodeResponseUrl authResponse =
            new AuthorizationCodeResponseUrl(fullUrlBuf.toString());
        // check for user-denied error
        if (authResponse.getError() != null) {
          // authorization denied...
        } else {
          // request access token using authResponse.getCode()...
            String code = authResponse.getCode();
            GoogleTokenResponse response = new GoogleAuthorizationCodeTokenRequest(HTTP_TRANSPORT,
                    JSON_FACTORY, CLIENT_ID, CLIENT_SECRET, code, redirectUrl).execute();
            String tokenAndExpiresInSeconds = response.getAccessToken() + "," + response.getExpiresInSeconds();
            return tokenAndExpiresInSeconds;
        }
```

It is a web application but hosted locally and accessed though localhost. The goal is to let end user to access his own Google Drive Spread Sheet and Fusion table.

If it is not possible to hide it, then:
1. Is it break the Google Agreement:
https://developers.google.com/terms/
`Developer credentials (such as passwords, keys, and client IDs) are intended to be used by you and identify your API Client. You will keep your credentials confidential and make reasonable efforts to prevent and discourage other API Clients from using your credentials. Developer credentials may not be embedded in open source projects.`

2. If it does, is there any alternative API provided by Google to address this issue. I checked the Google Sign-In, but seems it also need the client_secret. I also tried the sample project to access the service though command line, but the sample project itself won't compile since it is using old version of the client API.

**Comment by mattwhisenhunt** [comment]
Most open source projects that deal with keys or crypto secrets have assumptions built in about where they should be and then include an initial setup process to guide the user/admin in installing those keys in a secure fashion. The gamut runs from simply using environment variables to complex key management systems.

**Comment by wetneb** [comment]
@mattwhisenhunt thanks for your reply! In our case, the software is installed and run directly by the end user, who does not have the skills to do obtain the keys themselves. Think of it like LibreOffice: how would you add a Google Sheets importer/exporter to LibreOffice? You cannot expect users to go through the OAuth registration process when they install the software before they can use this functionality, can you?

**Comment by mattwhisenhunt** [comment]
It sounds like the kind of solution that should live on [Google Cloud](https://cloud.google.com/) instead of being distributed in the form of source code (or even jars for that matter) to end users' devices.

**Comment by jackyq2015** [comment]
@mattwhisenhunt Thank for the advice. This software is hosted on github and completely free to download and use by end user on there desktop. It is not commercial.  So Google Cloud might not be an option for us. Any other option from the code/API aspect?

**Comment by mattwhisenhunt** [comment]
When I browse _Connect apps to Drive_ in My Drive all the apps I see, even Fusion Tables, are web apps that don't need to distribute their client identity.

Imagine borrowing a book from the library and leaving it on the busiest street corner in your town. It is not just that it is against the rules, you would be accountable for anything that happened to the book without any oversight of who was using it or how.

**Comment by jackyq2015** [comment]
@mattwhisenhunt I agree that developer should hold the accountability of the key in term of how will be using it and how to use it. But given our current way of deployment and current API provided by Google, any recommendation we can do to achieve this? Thanks

**Comment by igorpisarev** [comment]
I had the same question and found that Google's OAuth2 endpoints support PKCE as an alternative to supplying a client secret:
https://developers.google.com/identity/protocols/OAuth2InstalledApp#create-code-challenge
But this mode does not seem to be covered by the Java API client. Is it planned to add support for this?

**Comment by mattwhisenhunt** [comment]
@igorpisarev, thanks. TIL about PKCE.

No plans to add it. We are trying not to add more features to this library, just fix critical bugs and offer maintenance and support where they are needed.

**Comment by LindaLawton** [comment]
This might help [Can I really not ship open source with Client ID?](https://stackoverflow.com/a/28109307/1841839)
