### ISSUE TITLE
Infinite cycle with MediaHttpDownloader setContentRange download

### ISSUE THREAD

**Issue by sbespalko** [googleapis/google-api-java-client#1101]
When trying to
```
downloader.setContentRange(0, fileSize / 2);
downloader.download();
```
The process never ends, because of
`mediaContentLength` always is maximum content Range and expression: 
`if( mediaContentLength <= nextByteIndex ) { ... return; }`
never give `true`

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue.
Are you building from source or using a release/snapshot? Is this bug related to [this commit](https://github.com/google/google-api-java-client/commit/3196df8d1ddcc36ace151241ce313b9fd7d26ada) I merged recently?

**Comment by alvazai** [comment]
I have exactly the same problem. I started palying with Google Drive JAVA API and everything is quite satisfactory so far with the exception of this problem. I understand that the same goal (partial file download) can be achieved by using lower level HTTP requests but I am unfamiliar with HTTP. 

Here is my code:

public byte[] downloadPartial(String googleID, long start, long size) throws GoogleDriveClientException{
         try {
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            Drive.Files.Get get = driveService.files().get(googleID);
            MediaHttpDownloader downloader = get.getMediaHttpDownloader();
            downloader.setContentRange(start, start+size-1);
            get.executeMediaAndDownloadTo(bos);
            return bos.toByteArray();
         } catch (IOException ex) {
            Logger.getLogger(GoogleDriveProxy.class.getName()).log(Level.SEVERE, null, ex);
            throw new GoogleDriveClientException("Failure downloading file: " + ex.getMessage());
        }
    }   

If I comment the line  
       downloader.setContentRange(start, start+size-1);
everything works but of course the whole file content is downloaded

**Comment by alvazai** [comment]
So basically I am asking for help. Can anybody suggest few lines of Java code to set the Content Range in some other way, before I take great pains to understand HTTP
