### ISSUE TITLE
Please support HTTPS proxies and self-signed certificates

### ISSUE THREAD

**Issue by nahuellofeudo** [googleapis/google-api-java-client#1114]
When these libraries try to connect to googleapis.com through HTTPS proxies, they use to validate the server's certificate a cacerts file embedded in google-client-api-x.y.z.jar itself.

The file is src/main/resources/com/google/api/client/googleapis/google.jks. Because this file is packaged in the same jar as the client code, it's not possible to override it or inject the CA's certificates to make the client recognize the proxy's certificates.

As a result, these libraries cannot be used behind a proxy when a plain HTTP proxy is not an option.

Please provide a way to instruct these client libraries to either use the standard Java cacerts file or a way to provide extra certificates to be added to the list of valid CAs at run time.

**Comment by JustinBeckwith** [comment]
👋 @mattwhisenhunt can we prioritize a fix for this one? Seems it's causing some customer pain.

@jadekler where are we with the release process for the library?  Is this one of the ones that's backed up?

**Comment by jadekler** [comment]
@JustinBeckwith Emailed you.

**Comment by mpiyush42** [comment]
Waiting on this fix..

**Comment by mattwhisenhunt** [comment]
I am sorry this question slipped through the cracks.

This class of customizations is addressed through [pluggable transports](https://developers.google.com/api-client-library/java/google-http-java-client/transport).

In this case if you are wanting to use your own jks file, the approach would be to create a line for line copy of [GoogleNetHttpTransport](https://github.com/google/google-api-java-client/blob/dev/google-api-client/src/main/java/com/google/api/client/googleapis/javanet/GoogleNetHttpTransport.java) that calls `trustCertificatesFromJavaKeyStore` instead of `trustCertificates`.

I am going to have to dig a little more to suggest how to use standard Java cacert files, but the approach is the same, return a instance of a class derived from `HttpTransport`

**Comment by JustinBeckwith** [comment]
Ok, so digging in here.  We're blocked on shipping this library until we work out #1084.  After that, we need to have someone fix this one.  I doubt this will happen before Q3.

**Comment by nahuellofeudo** [comment]
@mattwhisenhunt: the problem with the approach you suggest is that this client code isn't being called by custom code but from other GCP client libraries, so even creating a line-by-line copy of the class that does what you suggest it would be impossible to call the new code.

**Comment by chingor13** [comment]
@nahuellofeudo Sorry for the delay in getting to this. Is there a particular client you're having an issue with?

`com.google.api.client.googleapis.javanet.GoogleNetHttpTransport` is an helper to create a `HttpTransport` instance and is not a dependency used in either `com.google.cloud` or `com.google.apis`. 

Example for BigQuery (from com.google.cloud):
```java
HttpTransportFactory transportFactory = () -> {
  // TODO: handle IOException, GeneralSecurityException
  InputStream inputStream = new FileInputStream("/path/to/keystore");
  String storePass = "some passcode";
  return new NetHttpTransport.Builder()
      .trustCertificatesFromJavaKeyStore(inputStream, storePass).build();
};
HttpTransportOptions transportOptions = HttpTransportOptions.newBuilder()
    .setHttpTransportFactory(transportFactory)
    .build();
BigQuery bigquery = BigQueryOptions.newBuilder()
    .setTransportOptions(transportOptions)
    .build().getService();
```

**Comment by nahuellofeudo** [comment]
This bug was originally found when running Dataflow jobs. Dataflow uses the GCS client libraries to stage files, and these operations failed because of this bug.

**Comment by chingor13** [comment]
google-http-client add support for customer supplied certificates (mTLS) in [1.38.0](https://github.com/googleapis/google-http-java-client/releases/tag/v1.38.0). 

An example of using custom proxies: https://github.com/googleapis/google-auth-library-java#configuring-a-proxy
