### ISSUE TITLE
AbstractGoogleClient.batch() uses null request initializer instead of the one passed when creating service ?

### ISSUE THREAD

**Issue by rgrebski** [googleapis/google-api-java-client#1115]
When working with Gmail java client I noticed that httpRequestInitializer used during creation of service is not used in _AbstractGoogleClient.batch() _ 

```
  public final BatchRequest batch() {
    return batch(/*httpRequestInitializer*/ null);
  }
```

Shouldn't the httpRequestInitializer passed during creation of service be passed ? It could be accessed via:

> getRequestFactory().getInitializer()

So the resulting code in _AbstractGoogleClient_ would look like:
```
  public final BatchRequest batch() {
    return batch(/*httpRequestInitializer*/ getRequestFactory().getInitializer());
  }
```

Let me know if that makes sense, if so I can create PR

**Comment by sduskis** [comment]
@rgrebski, it looks like there are defaults in place already.  I'm going to suggest that we keep things as is, unless there's an actual problem.
