### ISSUE TITLE
Google contacts doesn´t work with setStartIndex

### ISSUE THREAD

**Issue by dacilsk** [googleapis/google-api-java-client#1116]
When i put setStartIndex() in the Query, it doesn´t works always it begin with the first result.
Here is the code.

    `ContactsService myService = new ContactsService("Project_Name");

	URL feedUrl = new URL("https://www.google.com/m8/feeds/contacts/default/full?v=3.0");

	Credential credential = GoogleContactsAPI.getInstance().getCredential(item);
	myService.setOAuth2Credentials(credential);
					
	ContactQuery query = new ContactQuery(feedUrl);
	query.setStringCustomParameter("q", parameter);
					
	int maxresult = loadConfig.getLimit();
	int startIndex = loadConfig.getOffset();
					
	if(startIndex == 0) {
		startIndex = 1;
	}
					
	query.setMaxResults(maxresult);
	query.setStartIndex(startIndex);
					
	ContactFeed resultFeed = myService.getFeed(query, ContactFeed.class); 
				
	int totalItems = resultFeed.getTotalResults();
	List<ContactEntry> entries = resultFeed.getEntries();`

**Comment by mattwhisenhunt** [comment]
Hi @dacilsk,

This client isn't meant for a GData API like Contacts. If you need to stick with GData check out https://github.com/google/gdata-java-client.

If you are ready to use the [People API](https://developers.google.com/people/) then this is the client library for you. Let us know if you have anymore questions.
