### ISSUE TITLE
package com.google.api.client.json.gson does not exist

### ISSUE THREAD

**Issue by aaronmefford** [googleapis/google-api-java-client#1138]
Seems the maven dependencies are not quite complete.   After adding the following to my pom.xml file

        <dependency>
          <groupId>com.google.apis</groupId>
          <artifactId>google-api-services-analyticsreporting</artifactId>
          <version>v4-rev124-1.23.0</version>
        </dependency>

When trying to build the HelloAnalyticsReporting sample, I get the following error:

package com.google.api.client.json.gson does not exist

**Comment by chingor13** [comment]
@aaronmefford The service clients all use [google-http-java-client](https://github.com/google/google-http-java-client) for the underlying HTTP calls. That library has adapters for multiple JSON encoder/decoder plugins (gson, Jackson) and so they are not declared as dependencies. If you're trying to use the gson JSON adapter you will want to add the [gson adapter](https://mvnrepository.com/artifact/com.google.http-client/google-http-client-gson) with something like:

```
<dependency>
    <groupId>com.google.http-client</groupId>
    <artifactId>google-http-client-gson</artifactId>
    <version>1.23.0</version>
</dependency>
```

**Comment by aaronmefford** [comment]
I was just trying to build the example code, and it does not build as is.  Thought you might want to know, fix it if you will.  If it were my repo I wouldn't want sample code to not run out of the gate.

**Comment by chingor13** [comment]
Thanks for clarifying. I assume you're referring to [the Maven section here](https://developers.google.com/api-client-library/java/apis/analyticsreporting/v4) linked from [this sample](https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/installed-java#2_install_the_client_library)?

**Comment by aaronmefford** [comment]
Yes.  Sorta.

I actually ended up on the V3 version which also has other errors in the code.

https://developers.google.com/analytics/devguides/reporting/core/v3/quickstart/service-java

It references an AnalyticsReporting type that does not exist, at least in that version, the correct type was Analytics with some trial and error.  I couldn't find anywhere that seemed appropriate to report it.  

But regarding the maven problem, yes that maven snippet was not adequate to build the sample code.

**Comment by sduskis** [comment]
@aaronmefford, thanks for the clarification.

This issue is better handled by reporting a bug on the developers.google.com site, so I went ahead and submitted a bug.  We'll work with the team that manages that page.
