### ISSUE TITLE
cannot access class  android.support.v4.app.FragmentActivity when i migrate to androidx

### ISSUE THREAD

**Issue by Kadanza** [googleapis/google-api-java-client#1150]
I have error  "cannot access class android.support.v4.app.FragmentActivity "    in

 GoogleApiClient.Builder(this)
                .enableAutoManage(this, this)
                .addApi(Auth.GOOGLE_SIGN_IN_API, gso)
                .build()

I migarete to androidx and  use library 
implementation('com.google.api-client:google-api-client-android:1.24.1') 

I think 
GoogleApiClient require android.support.v4.app.FragmentActivity, but i have  only androidx.appcompat.app.AppCompatActivity.  Paths not match.  How to resolve this problem?  

You should update your projects for androidx

**Comment by ashikazeez** [comment]
upgrade your version to ` implementation 'com.google.android.gms:play-services-auth:16.0.1'`

**Comment by cbaezenko** [comment]
I have the exactly same problem, I did not understand, how to fix the problem?, my dependencies are this:
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'com.google.android.gms:play-services-auth:16.0.1'
