### ISSUE TITLE
Cannot avoid listing files inside archive files

### ISSUE THREAD

**Issue by bobnewmark** [googleapis/google-api-java-client#1156]
Hello,

when getting all files from Google Drive, you automatically get all files contained in zip or 7z archives.
It may be correct behaviour from one side, but it's unavoidable behavior from the other side. Besides it's very inconvenient in most cases.
Of course you may filter them out later, but it's not optimal.
May be there's a way not to list files from inside the archives?

Thanks.

**Comment by elharo** [comment]
This doesn't seem in any way related to this product.

**Comment by bobnewmark** [comment]
My bad, you're right
