### ISSUE TITLE
how to resuming an interrupted upload by api

### ISSUE THREAD

**Issue by kbboss** [googleapis/google-api-java-client#1159]
I use it to resumed upload file . but When  Wife disconnect ,the file need restart to be uploaded from 0; 

```
File fileMetadata = new File();
        fileMetadata.setName(javaSrcFile.getName());
        String type = MimeTypeMap.getSingleton().getMimeTypeFromExtension(FileUtils.getFileExtension(javaSrcFile));
        fileMetadata.setParents(Collections.singletonList(folderId));
        FileContent mediaContent = new FileContent(type, javaSrcFile);
        Drive.Files.Create task = service.files().create(fileMetadata, mediaContent)
                .setFields(FILE_CREATE_FIELD);
        task.getMediaHttpUploader().setDirectUploadEnabled(false).setProgressListener(progressLst);
        File file = task.execute();
```

**Comment by marcus-hiles** [comment]
@kbboss can you provide more details about your programming frameworks here?

**Comment by chingor13** [comment]
These clients already implement the resumable upload protocol for all Google APIs that support it. You can find more information https://github.com/googleapis/google-api-java-client/wiki/Media-Upload. For additional control, you should be able to [set a backoff strategy](https://github.com/googleapis/google-http-java-client/wiki/Exponential-Backoff) so it will continue to retry sending chunks of your file in flakey network conditions.
