### ISSUE TITLE
google-api-client can't fallback from ipv6 to ipv4

### ISSUE THREAD

**Issue by eyanpen** [googleapis/google-api-java-client#1172]
Our env doesn't support IPV6. 

When performing DNS query (accounts.google.com, fcm.googleapis.com) to resolve IP-address for FCM server,  google-api-client sends both A and AAAA queries to google DNS server.   The DNS server  provides both IPv4 and IPv6 IP-addresses, google-api-client chooses IPv6 to access FCM by the java configuration:  -Djava.net.preferIPv6Addresses=true .

Because our network doesn't support IPv6, then it fails to connection FCM.  **However, google-api-client should fallback to ipv4 if ipv6 doesn't work.**

**Comment by chingor13** [comment]
If your environment doesn't support IPv6, then why set `-Djava.net.preferIPv6Addresses=true`? The DNS resolution is handled by the transport layer (which in your case appears to be the `java.net` adapter).
