### ISSUE TITLE
Filename is blank when importing cost data .csv file via Analytics Management API

### ISSUE THREAD

**Issue by markusheiden** [googleapis/google-api-java-client#1189]
#### Environment details

- Java version: 1.8
- google-api-java-client version: 1.23.0

#### Steps to reproduce

Uploading data to Analytics via their Java-API:
```java
    UploadData uploadData = analytics.management().uploads().uploadData(
       accountId, webPropertyId, dataSourceId,
       new FileContent("application/octet-stream", csvFile));
```

The reason this doesn't work is IMO, that the FileContent#getFile is never used to extract the name of the "csvFile". Even better would be to pass the file name explicitly to any AbstractInputStreamContent.

#### Any additional information below

Copied from the same issue in the google-api-python-client:

This was originally raised as an issue against Google Analytics itself:

https://issuetracker.google.com/issues/35353754

It was found there that the issue is with the api client stripping the filename from the POST body, so I'm raising this as an issue here, potentially to get a better response.

**Comment by LindaLawton** [comment]
This is a known issue and not related to the library [Management API Cost Data Upload .csv Doesn't Have Filename](https://issuetracker.google.com/issues/35353754)

**Comment by markusheiden** [comment]
I cross posted this issue, because the name of the file passed to FileContent will be ignored when creating the request. This makes it impossible for the analytics api client to pass the file name to its endpoint. If this client lib has another proper way of passing the file name, then please tell me and close this issue.

**Comment by chingor13** [comment]
1. The name of the uploaded file does not appear to be used by the analytics management API.

2. These client libraries are generated from the [API specification](https://github.com/googleapis/discovery-artifact-manager/blob/5f26037678b0327fa2b00ff226ab9dcb4edf9d95/discoveries/analytics.v3.json#L6750-L6805) of the service. Services that normally care about the file name define the file name as a parameter to the API.
