### ISSUE TITLE
googleCredential fails on Android

### ISSUE THREAD

**Issue by steve78b** [googleapis/google-api-java-client#1220]
Thanks for stopping by to let us know something could be better!

GoogleCredential tries to use the Android/Apache version of Base64, not the one in the dependency. 
As this version is old, it doesn't have the method decodeBase64. 

This fails on the emulators and on a real Android device.

The code in client.util.base64 explicitly refers to the apache commons version of Base64, but this is not found at run-time.

#### Environment details

- OS:  Android 6 & 7
- Java version:  1.8.0
- google-api-java-client version: 27 

#### Steps to reproduce

private static String getAccessToken(InputStream gc) throws IOException {
        GoogleCredential googleCredential = GoogleCredential
                .fromStream(gc)
                .createScoped(Arrays.asList(SCOPES));

#### Stacktrace

Caused by: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in
   class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration 
   of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
        at com.google.api.client.util.Base64.decodeBase64(Base64.java:101)
        at com.google.api.client.util.PemReader.readNextSection(PemReader.java:106)
        at com.google.api.client.util.PemReader.readFirstSectionAndClose(PemReader.java:135)
        at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.privateKeyFromPkcs8(GoogleCredential.java:904)
        at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.fromStreamServiceAccount(GoogleCredential.java:877)
        at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.fromStream(GoogleCredential.java:260)
        at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.fromStream(GoogleCredential.java:226)
        at me.steve.TumblerListen.gCredTask.getAccessToken(gCredTask.java:33)
```


#### External references such as API reference guides used
Libraries in Gradle dependency list include
   implementation  'commons-codec:commons-codec:1.11'
    implementation 'com.google.http-client:google-http-client:1.27.0'
    implementation 'com.google.api-client:google-api-client:1.27.0'
- ?

#### Any additional information below



Thanks!

**Comment by Tyljlove** [comment]
Having same issue. Any update?

**Comment by steve78b** [comment]
I found a bypass. 

I downloaded a lot of jar files.
In studio64 project structure I then included them, one by one, until the bug went away.

This is what my gradle app file ended up with

dependencies {
....
  implementation files('libs/google-api-client-android-1.24.1.jar')
    implementation files('libs/google-api-client-1.24.1.jar')
    implementation files('libs/google-oauth-client-1.24.1.jar')
    implementation files('libs/google-http-client-1.24.1.jar')
    implementation files('libs/google-api-client-jackson2-1.24.1.jar')
    implementation files('libs/google-api-client-gson-1.24.1.jar')
    implementation files('libs/google-http-client-jackson2-1.24.1.jar')
    implementation files('libs/jackson-core-2.9.2.jar')
}

Experiment to get the minimum.

**Comment by Tyljlove** [comment]
I've tried implementing this, and I am getting the same issues.. Any tips?

**Comment by steve78b** [comment]
Here it is 
in the main gradle I have Google and Jcenter repositories.


[gradle.txt](https://github.com/googleapis/google-api-java-client/files/2685945/gradle.txt)

**Comment by chingor13** [comment]
The google-http-client was not correctly shading/jarjar'ing the apache common-codec version and it conflicts with the built-in android one.

**Comment by chingor13** [comment]
Downgrading to 1.25.0 or earlier should work until 1.28.0 is released (soon).
