### ISSUE TITLE
CloudResourceManager v1 and v2 package collision

### ISSUE THREAD

**Issue by pdube** [googleapis/google-api-java-client#1236]
#### Environment details

- Java version: 8
- google-api-java-client version (artifact : version): 
google-api-services-cloudresourcemanager : v2-rev20181015-1.28.0
google-api-services-cloudresourcemanager : v1-rev20181015-1.28.0

Hi all, 

I am not sure that this is the right place for this, but I can't find the source repo for `google-api-services-cloudresourcemanager`.  If you know where it is hosted or where I should open the issue, please let me know. If this is the right place, here it goes:

The v1 CloudResourceManager class supports the `projects` and `organizations` APIs, but not `folders` (makes sense cause it's a v2 API) [1]. So, if you want to manage the `folders` API, you need to use the v2 CloudResourceManager class. However, the problem is that the v2 CloudResourceManager class doesn't support `projects` or `organizations` [2]. Since it's the same artifact, but a different version, it won't work out of the box.

I think it might be possible to do some shading to have both versions of the artifact present, but it looks like a design flaw. Either the v1 APIs could be added to the v2 class, or the artifact could be split into 2 different artifacts, or the package `com.google.api.services.cloudresourcemanager` could become `package com.google.api.services.cloudresourcemanager.v1` and `package com.google.api.services.cloudresourcemanager.v2`. 

I am open to help with this issue. What do you think? Is there anything I am missing?

#### External references such as API reference guides used

[1] - https://developers.google.com/resources/api-libraries/documentation/cloudresourcemanager/v2/java/latest/
[2] - https://developers.google.com/resources/api-libraries/documentation/cloudresourcemanager/v1/java/latest/

- https://developers.google.com/api-client-library/java/apis/cloudresourcemanager/v2

**Comment by jbharter** [comment]
Can we get an update on this? Designing around it is becoming kindof annoying

**Comment by codyoss** [comment]
Hey @pdube I think you are right that shading does sound like your best option at the moment. If you would like to file and issue for that project I suggest using [the cloud issue tracker](https://cloud.google.com/support/docs/issue-trackers). If you search `Resource Manager` on that page you can look at open issues and/or open your own.

**Comment by pdube** [comment]
Thanks @codyoss. I'll take a look at the open issues

**Comment by pdube** [comment]
I have created it here : https://issuetracker.google.com/issues/142779997

**Comment by codyoss** [comment]
Awesome, thanks @pdube! I will close this issue as we now have this properly tracked on that issue tracker.
