### ISSUE TITLE
Clarify google api java client documentation

### ISSUE THREAD

**Issue by Dularl** [googleapis/google-api-java-client#1245]
It's not an actual bug but seems like the documentation is a bit outdated. 
The page I am talking about is https://developers.google.com/api-client-library/java/google-api-java-client/oauth2 .

 It was updated on 09.13.2018 . However it still mentions google plus related stuff which I think it's not relevant anymore or at least it's very confusing as Google+ APIs are shutting down.

Could you please verify if that's the case?

**Comment by elharo** [comment]
Makes sense. Anyone know whether the document in google3 is the canonical source, or is that copied in from Github?

**Comment by chingor13** [comment]
Content from those pages has been migrated into this repo (and related libraries' repositories) wiki. The links from the README are being fixed in #1353
