### ISSUE TITLE
update credentials documentation

### ISSUE THREAD

**Issue by akostadinov** [googleapis/google-api-java-client#1366]
There is a problem with credentials documentation [1]. It points at oauth 2.0 [2] which refers to GoogleCredential [3]. And that is listed as **Deprecated**.

Please somebody update to a non-deprecated example.

[1] https://developers.google.com/api-client-library/java/google-api-java-client/dev-guide
[2] https://developers.google.com/api-client-library/java/google-api-java-client/oauth2
[3] https://googleapis.dev/java/google-api-client/latest/com/google/api/client/googleapis/auth/oauth2/GoogleCredential.html

**Comment by akostadinov** [comment]
This is what I figure out so far. Not yet sure how well it works but here I paste in **groovy**:
```
import com.google.auth.oauth2.GoogleCredentials;
import com.google.auth.oauth2.AccessToken;
import com.google.auth.http.HttpCredentialsAdapter;

import com.google.api.client.googleapis.javanet.GoogleNetHttpTransport;
import com.google.api.client.json.jackson2.JacksonFactory;

GoogleCredentials credentials = GoogleCredentials.fromStream(new FileInputStream("/path/to/auth/gsheets.json")).createScoped(SheetsScopes.SPREADSHEETS);

final String APPLICATION_NAME = "example app";

Sheets sheets = new Sheets.Builder(
          GoogleNetHttpTransport.newTrustedTransport(),
          JacksonFactory.getDefaultInstance(),
          new HttpCredentialsAdapter(credentials)).
          setApplicationName(APPLICATION_NAME).
          build();
```

Hope it helps somebody get started quickly.

**Comment by stefan-zh** [comment]
Thank you! It worked for me!

**Comment by chingor13** [comment]
We also need to update the sample code to use the non-deprecated version.
