### ISSUE TITLE
Version 1.30.3 causes crash on Android < 8.0 when using FileDataStoreFactory from transitive google-http-java-client dependency

### ISSUE THREAD

**Issue by alapshin** [googleapis/google-api-java-client#1382]
#### Environment details

1. OAuth2
2. Android < 8.0 (API < 26)
3. Java version:
4. google-api-client version(s): 1.30.3

#### Steps to reproduce
1. Update google-api-java-client to 1.30.3 (from 1.30.2)
2. Try to create new instance of `FileDataStore` for `AuthorizationCodeFlow.Builder`
3. Launch application on device with Android < 8.0
4. Application crashes with attached stacktrace

#### Code example

```java
new FileDataStoreFactory(new File(context.getFilesDir(), "credentials"))
```

#### Stack trace
```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/attribute/PosixFilePermission;
        at com.google.api.client.util.store.FileDataStoreFactory.setPermissionsToOwnerOnly(FileDataStoreFactory.java:141)
        at com.google.api.client.util.store.FileDataStoreFactory.<init>(FileDataStoreFactory.java:77)
```

#### Any additional information below

As far as I can tell is caused by following change in google-http-java-client:
https://github.com/googleapis/google-http-java-client/pull/557 which was released as part of 1.31.0

Version 1.30.3 of google-api-client in turn pulls google-http-java-client 1.31.0:
https://github.com/googleapis/google-api-java-client/pull/1347

As a result if application doesn't have explicit dependency on earlier version of  google-http-java-client new version is used and  it causes crash on devices with Android < 8.0 since NIO is not available until API 26.

**Comment by chingor13** [comment]
Unfortunately, you'll have to either lock your google-http-client to 1.30.2 or provide your own `DataStoreFactory` implementation. We will update the docs in google-http-client.

**Comment by chingor13** [comment]
In com.google.http-client:google-http-client-android [v1.36.0](https://github.com/googleapis/google-http-java-client/releases/tag/v1.36.0) we added back an Android-compatible `FileDataStoreFactory`
