### ISSUE TITLE
'com.google.api-client:google-api-client:1.30.6 

### ISSUE THREAD

**Issue by GuyDviri** [googleapis/google-api-java-client#1455]
Crash my endpoint Wapi -thread - 9 error

**Comment by codyoss** [comment]
Could you please provide some more information like a stack trace? Also, can you please try to upgrade to `1.30.7` and let me know if you still have your issue?

**Comment by GuyDviri** [comment]
this the error on 1.30.6 
FATAL EXCEPTION: Thread-10 
java.lang.ExceptionInInitializerError .wAPI.WAPI.<clinit>(WAPI.java:46)

1.30.7 : seems to have no issue.

**Comment by codyoss** [comment]
Glad that fixed it for you!
