### ISSUE TITLE
How to get Server Authorization code using Google Client Api

### ISSUE THREAD

**Issue by jakeershaik217** [googleapis/google-api-java-client#1460]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Comment by heatherrenee1983** [comment]
Help

**Comment by codyoss** [comment]
I think you might find the docs on this page useful: https://developers.google.com/api-client-library/java

If this does not help feel free to reopen with more details.
