### ISSUE TITLE
CLIRR errors at head

### ISSUE THREAD

**Issue by elharo** [googleapis/google-api-java-client#1500]
[ERROR] 7006: com.google.api.client.googleapis.extensions.android.gms.auth.GooglePlayServicesAvailabilityIOException: Return type of method 'public com.google.android.gms.auth.GoogleAuthException getCause()' has been changed to java.lang.Throwable
[ERROR] 7006: com.google.api.client.googleapis.extensions.android.gms.auth.GooglePlayServicesAvailabilityIOException: Return type of method 'public java.lang.Throwable getCause()' has been changed to com.google.android.gms.auth.GoogleAuthException

**Comment by chingor13** [comment]
I'm not able to reproduce this. Also, `GooglePlayServicesAvailabilityIOException` has not changed since June 2017
