### ISSUE TITLE
Is there any way to watch vacation settings changes of gmail settings ?

### ISSUE THREAD

**Issue by Code2Life** [googleapis/google-api-java-client#1532]
I'm developing an app to sync user's status, so I want to get realtime OOO state (Out Of Office).
Besides OOO calendar event, gmail users can set vacation/autoReply, I know there is a nice API to fetch this setting ([https://developers.google.com/gmail/api/v1/reference/users/settings/getVacation](https://developers.google.com/gmail/api/v1/reference/users/settings/getVacation)), but how could I get realtime notifications of this setting change, just like Google calendar resource watch/push notification mechanism?

**Comment by Code2Life** [comment]
![image](https://user-images.githubusercontent.com/14833440/83828539-7c4f2400-a713-11ea-9936-d74efbb1f164.png)

I didn't found how to watch this setting in Google API documents, could this be possible?

**Comment by chingor13** [comment]
To my knowledge, there is no such built-in change listener for this field.

**Comment by Code2Life** [comment]
Gotcha, thanks a lot.
