### ISSUE TITLE
Need help with License Manager API

### ISSUE THREAD

**Issue by hari1692** [googleapis/google-api-java-client#1533]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.
I contacted support yet they redirected me here. I need help in writing java code using google client library for License Manager api.

**Comment by chingor13** [comment]
If you have an actual question, we can try to help here.

If you do in fact have a support contract, then a customer engineer can help walk through examples.

**Comment by hari1692** [comment]
I need help in writing java code using google client library for License Manager api.

**Comment by hari1692** [comment]
> If you have an actual question, we can try to help here.
> 
> If you do in fact have a support contract, then a customer engineer can help walk through examples.

I need help in writing java code using google client library for License Manager api.
