### ISSUE TITLE
After deleting an event, get() call is being successful

### ISSUE THREAD

**Issue by KSVarun** [googleapis/google-api-java-client#1535]
#### Environment details

1. Google calendar API
2. OS type and version: Mac OS
3. Java version: 1.8
4. google-api-client version(s): 1.30.9

#### Steps to reproduce

  1. Create an event with `Event event = service.events().insert(calendarId, event).execute();`
  2. Delete the event with `service.events().delete(calendarId, event.getId()).execute();`
  3. Get the event with `event = service.events().get(calendarId, event.getId()).execute();`

#### External references such as API reference guides
https://developers.google.com/calendar/v3/reference/events/insert
https://developers.google.com/calendar/v3/reference/events/delete
https://developers.google.com/calendar/v3/reference/events/get

.get() call should fail right? after deleting the event. But I am able to get a successful response with appropriate details of previously created event.

Thanks!

**Comment by KSVarun** [comment]
It seems deleting an event won't actually delete the event but just tags it as cancelled. Hence when we do a get call we will be able to fetch the event.

Correct me if am wrong.

**Comment by burkedavison** [comment]
Closing this issue as we are unable to provide adequate customer support through this forum. If you feel there is a bug or a feature request associated with this ticket, please open a new issue. Otherwise, https://cloud.google.com/support is best able to provide timely answers to API-specific questions.
