### ISSUE TITLE
404 on every call through BatchRequest

### ISSUE THREAD

**Issue by ikseo** [googleapis/google-api-java-client#1571]
I get 404 ("Response status code does not indicate success: 404 (Not Found).") on every call through BatchRequest.

I saw https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html.

Global HTTP Batch Endpoints (www.googleapis.com/batch) is deprecated.

okay.

My source change HTTP Batch Endpoints(https://www.googleapis.com/batch/youtube/v3)

Uhm....

But on every call I heav got an error 404.
why not?

What I do incorrectly or it doesn't work at all ?
Thanks.

**Comment by lesv** [comment]
Is this still a problem for you?

**Comment by lesv** [comment]
From the blog post:


August 19, 2020: Revised guidance for Google Cloud client libraries and Apache Beam/Cloud Dataflow

August 12, 2020: Added guidance for Dataproc hadoop connector

July 13, 2020: Enumerate endpoints for JSON-RPC and Global HTTP Batch. Include examples of Non-Global HTTP Batch endpoints for contrast.

July 8, 2020: Limit usage of JSON-RPC and Global HTTP batch endpoints to existing projects only. Starting July 15 (JSON-RPC) and July 16 (Global HTTP Batch) we will no longer allow new projects to call these two endpoints. Projects with calls in the last 4 weeks will continue to work until the deadline of Aug 12, 2020.

Apr 23, 2020: gcloud min version has been updated

Apr 22, 2020: error injection planned for Apr 28 is CANCELLED, JSON-RPC and Global HTTP batch endpoint will perform normally. Next error injection window will be on May 26 as scheduled.

**Comment by lesv** [comment]
It looks like the endpoint was properly turned down.  Please reopen if you disagree.
