### ISSUE TITLE
GitHub CI of this repository is failing

### ISSUE THREAD

**Issue by suztomo** [googleapis/google-api-java-client#1691]
<img width="1103" alt="Screen Shot 2021-02-08 at 15 29 58" src="https://user-images.githubusercontent.com/28604/107278089-50fba200-6a23-11eb-8250-02eecdfb1517.png">

```
Error:  Failed to execute goal on project google-api-client-android: Could not resolve dependencies for project
com.google.api-client:google-api-client-android:jar:1.31.2: Failure to find com.google.android.google-play-services:google-play-services:jar:1
in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the 
update interval of central has elapsed or updates are forced -> [Help 1]
Error:  
```

https://github.com/googleapis/google-api-java-client/blob/master/.github/workflows/ci.yaml was last touched in July 2020. Why was it fine (e.g., [PR#1675](https://github.com/googleapis/google-api-java-client/pull/1675#partial-pull-merging)) until last week?

**Comment by suztomo** [comment]
But the .github/workflows/ci.yaml is a template-generated file. 

https://github.com/googleapis/google-api-java-client/pull/1695 fixes the "lint" job.

**Comment by chingor13** [comment]
We recently turned on GitHub actions in this repository. They are not required checks at this time.

For the google-play-services jar, this was [installed in the docker image](https://github.com/googleapis/testing-infra-docker/blob/5e2e57e54185e12ac15acc1d7a47569846b38971/java/java8/Dockerfile#L39-L48). At the time, the google-play-services was not available on Maven Central (it may be now)

**Comment by suztomo** [comment]
> We recently turned on GitHub actions in this repository.

Thanks. That explains why it was working fine until last week.

>  At the time, the google-play-services was not available on Maven Central (it may be now)

I still don't see the artifact available in Maven Central.  (There's an artifact somebody uploaded as `com.jdroidframework:google-play-services:0.6.0`)

<img width="1013" alt="Screen Shot 2021-02-10 at 15 39 27" src="https://user-images.githubusercontent.com/28604/107569316-2beb6880-6bb6-11eb-8344-c9bfeb73289e.png">


Yesterday I committed a change to call `.kokoro/install_dependencies.sh` https://github.com/googleapis/google-api-java-client/pull/1699/files#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddR19 . Feel free to revert this if there's a better way.

**Comment by suztomo** [comment]
@chingor13 I committed the recent PRs to fix the GitHub Actions checks. Now they succeeds. 

<img width="544" alt="Screen Shot 2021-02-12 at 10 03 54" src="https://user-images.githubusercontent.com/28604/107784579-9f59bb00-6d19-11eb-9c74-38e6d1f6978b.png">
