### ISSUE TITLE
Add API to set/validate End-to-End Checksum

### ISSUE THREAD

**Issue by vnorigoog** [googleapis/google-api-java-client#1724]
To Support Silent Data Corruption Detection (SDC), Google services support end-to-end Checksum.
Add API + library to allow client libs to set/validate end-to-end checksum

More info about SDC:
================
Undetected software bugs and CPU defects can corrupt or destroy critical Google and customer data. Such “Silent Data Corruption” (SDC) is the focus of GCP Reliability Efforts and of intense research and development aimed at preventing, detecting, reporting, and mitigating corruption within GCP community.

SDC resilience efforts have been prioritized across all  layers of GCP stack, all the way from Keystore to low level storage to well known public databases such as Spanner and Bigtable. Data corruption is often non-deterministic and it’s often hard to identify the root cause. Countermeasures such as replicated computation and end to end checksumming can help detect and mitigate the frequency and severity of such occurrences, but need to be designed carefully to avoid undue latency and throughput cost. The SDC program is building  a robust common monitoring system to report and analyze real time signals of data corruption

**Comment by vnorigoog** [comment]
How will this API be used
====================
By Java Http Clients to add checksum to the requests and to validate checksum on the responses received.

Do we have specific data on bugs caused by memory corruption
=================================================
Short answer: No
But memory corruption bugs are inherently impossible to attribute to a specific root cause.
Checksum is a widely used mechanism to check the data integrity.

**Comment by vnorigoog** [comment]
Question: Why TLS and other layers don't catch it.
===========================================================
Our E2E checksum solution is designed to be end-to-end in GCP: from Client to the Google Backend Service thru all intermediate points w/in google, who can (and some will) verify the checksum and reject the request/response if checksum is invalid.

**Comment by elharo** [comment]
1. Detailed, non-hypothetical examples needed. What are the endpoints? 
2. What is checksummed and how? That is, how does the wire format change?
      2a. How do you guarantee backwards compatibility with non-checksummed data?
3. What happens when a checksum doesn't match? Retry? Silently discard?
4. In what part of the pipeline is data corrupted? What does this add on top of existing mechanisms that detect data corruption such as TCP and TLS?
