### ISSUE TITLE
java.lang.NoSuchMethodError: com.google.api.client.http.HttpRequest.setResponseReturnRawInputStream(Z)Lcom/google/api/client/http/HttpRequest

### ISSUE THREAD

**Issue by plaidshirtakos** [googleapis/google-api-java-client#1753]
I got following error during execution of Quickstart: https://developers.google.com/gmail/api/quickstart/java

`java.lang.NoSuchMethodError: com.google.api.client.http.HttpRequest.setResponseReturnRawInputStream(Z)Lcom/google/api/client/http/HttpRequest`

I have imported following dependencies:
```
2021.03.23.  12:54           284 184 commons-codec-1.10.jar
2021.03.23.  12:54            61 829 commons-logging-1.2.jar
2021.03.23.  12:43           216 630 google-api-client-1.31.3.jar
2021.03.23.  12:47            15 488 google-api-client-extensions-1.6.0-beta.jar
2021.03.23.  12:45             5 007 google-api-client-jackson2-1.31.3.jar
2021.03.23.  12:45             4 663 google-api-client-java6-1.31.3.jar
2021.03.23.  12:45           166 608 google-api-services-gmail-v1-rev110-1.25.0.jar
2021.03.23.  12:54           275 197 google-http-client-1.27.0.jar
2021.03.23.  12:54             8 548 google-http-client-jackson2-1.27.0.jar
2021.03.23.  12:48            14 869 google-oauth-client-java6-1.31.4.jar
2021.03.23.  12:49             9 689 google-oauth-client-jetty-1.31.4.jar
2021.03.23.  12:54         2 442 625 guava-20.0.jar
2021.03.23.  12:54           766 123 httpclient-4.5.5.jar
2021.03.23.  12:54           325 500 httpcore-4.4.9.jar
2021.03.23.  12:54             8 782 j2objc-annotations-1.1.jar
2021.03.23.  12:54           323 848 jackson-core-2.9.6.jar
2021.03.23.  12:54            19 936 jsr305-3.0.2.jar
```

**Comment by chingor13** [comment]
[HttpRequest.setResponseReturnRawInputStream](https://googleapis.dev/java/google-http-client/latest/com/google/api/client/http/HttpRequest.html#setResponseReturnRawInputStream-boolean-) was introduced in google-http-client 1.29.0. Your current dependencies use 1.27.0.

The dependency tree for any single one of our artifacts should be correct at that point, so the dependency resolution is causing you to get an older version.

**Comment by plaidshirtakos** [comment]
@chingor13 : I just updated following dependencies: google-http-client-1.39.1 and google-http-client-jackson2-1.39.1, but problem still persists.
