### ISSUE TITLE
After updating to version (1.31.4), a CPU problem occurred.

### ISSUE THREAD

**Issue by junhoi-pk** [googleapis/google-api-java-client#1767]
#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types

> com.google.apis:google-api-services-androidpublisher:v3-rev20201125-1.31.0
> Use several functions provided in mainly Use the methods under AndroidPublisher.purchases().products().

2. OS type and version:  Amazon Linux release 2 (Karoo)
3. Java version: corretto 16
4. google-api-client version(s): v1.31.4

```
api("com.google.api-client:google-api-client:1.31.4")
api("com.google.apis:google-api-services-androidpublisher:v3-rev20201125-1.31.0")
```

I upgraded the version from 1.31.3 to 1.31.4.
As soon as the upgrade, cpu usage increased rapidly, and after checking the problem, I rolled back.

<img width="1043" alt="스크린샷 2021-04-13 오후 12 18 16" src="https://user-images.githubusercontent.com/6330405/114492343-65426200-9c53-11eb-96a1-726807b1da47.png">

**Comment by Neenu1995** [comment]
Hi,
Can you provide more information regarding what is causing the CPU usage?

**Comment by junhoi-pk** [comment]
I simply cannot guess under what circumstances the problem occurred.
However, most of the above libs use the payment confirmation method of the androidpublisher package.

Even when traffic is low at that time,
This method was called about 30 times per hour.

**Comment by junhoi-pk** [comment]
@Neenu1995 Hi

One more guess, I
I am using `https://github.com/firebase/firebase-admin-java`
I know that this library is dependent on `google-api-java-client`.

If I upgrade the `google-api-java-client` version, there is a problem here, so I think the cpu has risen.

My service uses a lot of message push through firebase-admin-java.

Additionally, the same issue occurred when I upgraded the version of `firebase-admin-java` from 7.2.0 to 7.3.0 today.

Firebase-admin-java 7.3.0 uses version 1.31.4 of google-api-java-client.

**Comment by junhoi-pk** [comment]
@Neenu1995 

As far as I can guess, the parts that have changed between versions are as follows.
`https://github.com/googleapis/google-api-java-client/commit/07346d8dfa955a40daf01b8fb17fe1d75dc2a998`

```
-       InputStream contentStream = response.getContent();
+       InputStream contentStream = new BufferedInputStream(response.getContent());
```

here
I guess it's a problem to create with `new` every time like `new BufferedInputStream(response.getContent())`.

Please tell me your opinion :)

**Comment by lesv** [comment]
@junhoi-pk I'm going to close this since there hasn't been any action on this for months, if you are still seeking assistance, it's probably better to ask this on StackOverflow and tag it android & firebase to get help.
