### ISSUE TITLE
GoogleIdTokenVerifier - get the reason why ID token is invalid

### ISSUE THREAD

**Issue by mkopylec** [googleapis/google-api-java-client#1777]
Hi.
Right now the [`GoogleIdTokenVerifier#verify`](https://github.com/googleapis/google-api-java-client/blob/master/google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleIdTokenVerifier.java#L183) returns `GoogleIdToken` or `null` if the token is invalid.
I need to know the reason why the token is invalid.
It can be implemented by throwing specific exception:
```java
enum IdTokenViolation {
   EXPIRED, INVALID_SIGNATURE, INVALID_FORMAT, EMPTY, etc.
}

public class InvalidIdTokenException extends Exception {
   public IdTokenViolation getViolation() { } 
}

public GoogleIdToken verify(token) throws InvalidIdTokenException
```
or by returning a result wrapper:
```java
enum IdTokenViolation {
   EXPIRED, INVALID_SIGNATURE, INVALID_FORMAT, EMPTY, etc.
}

public class IdTokenVerificationResult {
   public GoogleIdToken getIdToken() { } 
   public IdTokenViolation getIdTokenViolation() { } 
}

public IdTokenVerificationResult verify(token)
```
To maintain backward compatibility this could be implemented as a new method in `GoogleIdTokenVerifier`.
Is there any chance to get it done?

**Comment by cluesblues** [comment]
sounds like u got it figured out soon i can get around to it i stay  busy
working on a app that going be best social media app ever

**Comment by Neenu1995** [comment]
The [TokenVerifier](https://github.com/googleapis/google-auth-library-java#verifying-jwt-tokens-beta) in the google-auth-library-java is the more up-to-date implementation. Can you try using the TokenVerifier in the auth library?

**Comment by mkopylec** [comment]
It looks like it is what I'm looking for. I'll check it out.
