### ISSUE TITLE
UserRecoverableAuthIOException, starting application from getIntent() spins in UI

### ISSUE THREAD

**Issue by mikep01** [googleapis/google-api-java-client#1866]
package com.google.api.client.googleapis.extensions.android.gms.auth
UserRecoverableAuthIOException

Using as per the example in that file:
```
    } catch (UserRecoverableAuthIOException userRecoverableException) {
      myActivity.startActivityForResult(
          userRecoverableException.getIntent(), MyActivity.REQUEST_AUTHORIZATION);
    }
```
Previously this would open a (google supplied?) window that would allow the user to select and authorize their account.  Current behavior on various android versions is that the app opens and shows a spinning/loading icon with no content.

Android, various versions, current libraries and play services installed.  Built with:
```
    implementation 'com.google.android.gms:play-services-identity:17.0.1'
    implementation 'com.google.android.gms:play-services-location:18.0.0'
    implementation 'com.google.android.gms:play-services-basement:17.6.0'
    implementation 'com.google.android.gms:play-services-gcm:17.0.0'
    implementation 'com.google.android.gms:play-services-auth:19.2.0'
    implementation 'com.google.android.gms:play-services-base:17.6.0'
```

===

Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-java-client/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version:
3. Java version:
4. google-api-client version(s):

#### Steps to reproduce

  1. ?
  2. ?

#### Code example

```java
// example
```

#### Stack trace
```
Any relevant stacktrace here.
```

#### External references such as API reference guides

- ?

#### Any additional information below

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by lesv** [comment]
We answer questions about the generated API clients.  Android auth is probably best asked on Stackoverflow

**Comment by mikep01** [comment]
Wait, this isn't a question, it's a bug.  It looks like there's a problem either with the google "grant permission" cloud service, or a problem with the android library receiving it.
I have no idea to against which component this should be opened, can you direct me or route it appropriately?
