### ISSUE TITLE
"{Botname} is unable to process your request " error while handling card_click event on Google Chat

### ISSUE THREAD

**Issue by aniketKumar210** [googleapis/google-api-java-client#1874]
#### Environment Details
1. OS type and version: Ubuntu 18.04
2.  Java version: JDK 1.8
3. google-api-client version(s):1.32.1 

#### Steps to reproduce

On Sending response to the user:
`{actionResponse=
{type=UPDATE_MESSAGE}, 
text=botresponse, 
thread={name=spaces/gPifRwAAAAE/threads/ITDO-j7EFM8}
}`

even updating type to NEW_MESSAGE or sending card instead of text still result in same error.

![Screenshot from 2021-09-09 21-25-22](https://user-images.githubusercontent.com/86307559/132720717-8f3cec79-ad1f-4954-820d-dfd8f96d29fe.png)

Thanks!

**Comment by aniketKumar210** [comment]
Even though the response is delivered to the user still the Error is shown to the user.

**Comment by lesv** [comment]
@aniketKumar210 Please look at [How to get help](https://developers.google.com/chat/support) and file this there as they will be better able to help you.

**Comment by aniketKumar210** [comment]
sure, thanks
