### ISSUE TITLE
Required google-api-client-android dependency removed since #1703

### ISSUE THREAD

**Issue by UweTrottmann** [googleapis/google-api-java-client#1888]
#1703 appears to have [removed](https://github.com/googleapis/google-api-java-client/pull/1703/commits/cb25d0dd0b2a8d92f067d9e7fc312448ab72d20b) the required dependency on `google-api-client` and `google-http-client-android` from [`google-api-client-android/pom.xml`](https://github.com/suztomo/google-api-java-client/blob/master/google-api-client-android/pom.xml).

And after a quick look that PR also did some other weird adds/removals of dependencies from other POMs. E.g. I spotted `google-http-client-gson` replacing `google-http-client-jackson2` in `google-api-client-jackson2/pom.xml`.

Are these changes on purpose or accidental?

**Comment by suztomo** [comment]
@UweTrottmann  I might misrecognize google-api-client-android and google-http-client-android. What problem do you observe due to the missed dependency? I'd like to reinstall the dependency and setup a check/test to prevent it from recurring.

**Comment by UweTrottmann** [comment]
I had a deeper look at the `google-api-client-android` sources and it appears the `google-api-client` and `google-http-client-android` dependency are not really needed. So I made a mistake in saying they are "required".

My expectation was that `google-api-client-android` would always have a dependency on `google-api-client` just based on the similar name. But I guess only including what is actually required to compile makes sense.

The issue was that some of my code was using classes from `google-api-client`. The solution was to add an explicit dependency on `google-api-client` in addition to `google-api-client-android`.

**Comment by suztomo** [comment]
@UweTrottmann Thank you for the analysis and timely response! Yes, if you're using a class, then it's better to declare the dependency that holds the class (It's called "Used undeclared dependencies" in Maven. [A related Stackoverflow post](https://stackoverflow.com/questions/4565740/what-are-unused-undeclared-dependencies-in-maven-what-to-do-with-them)).

**Comment by UweTrottmann** [comment]
Sure! And thanks for the link. My project is using Gradle, but it appears at least [one plugin provides similar functionality](https://github.com/gradle-dependency-analyze/gradle-dependency-analyze).
