### ISSUE TITLE
Failing to use Federated authentication 

### ISSUE THREAD

**Issue by ismailsimsek** [googleapis/google-api-java-client#1891]
Following method failing to read federated authentication file 
[GoogleCredential.fromStream](https://github.com/googleapis/google-api-java-client/blob/main/google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleCredential.java#L228) 

used by [DefaultCredentialProvider.getCredentialUsingEnvironmentVariable](https://github.com/googleapis/google-api-java-client/blob/main/google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/DefaultCredentialProvider.java#L217
) 

related https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/471

**Comment by lesv** [comment]
@ismailsimsek Please try opening this in either https://github.com/googleapis/google-oauth-java-client or https://github.com/googleapis/google-auth-library-java
