### ISSUE TITLE
GCS: `setRootUrl` override does not apply to PUT requests in resumable uploads

### ISSUE THREAD

**Issue by medb** [googleapis/google-api-java-client#1908]
#### Environment details

1. OS type and version: Debian 10
1. Java version: 8u292
1. google-api-client version(s): 1.39.0

#### Steps to reproduce

  1. Override root URL using `Storage.setRootUrl("...")` method.
  2. Execute resumable upload.

#### Stack trace

```
Oct 26, 2021 5:42:51 AM com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.HttpResponse <init>
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 200 OK
Server: UploadServer
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
X-GUploader-UploadID: ADPycdtrIid39eNFjGnt570wYOCu3aCCy872EmJISL1_euGWONVNnyFR_FiFkZJebIh0WVNwx0_PlBZPzvV_Ll4S2e6JDHIlOA
Vary: X-Origin
Vary: Origin
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Content-Length: 0
Date: Tue, 26 Oct 2021 05:42:51 GMT
Location: https://storage.googleapis.com/upload/storage/v1/b/<BUCKET>/o?ifGenerationMatch=0&name=test-empty-04._COPYING_&uploadType=resumable&upload_id=ADPycdtrIid39eNFjGnt570wYOCu3aCCy872EmJISL1_euGWONVNnyFR_FiFkZJebIh0WVNwx0_PlBZPzvV_Ll4S2e6JDHIlOA
Content-Type: text/plain; charset=utf-8

Oct 26, 2021 5:42:51 AM com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.HttpRequest execute
CONFIG: -------------- REQUEST  --------------
PUT https://storage.googleapis.com/upload/storage/v1/b/<BUCKET>/o?ifGenerationMatch=0&name=test-empty-04._COPYING_&uploadType=resumable&upload_id=ADPycdtrIid39eNFjGnt570wYOCu3aCCy872EmJISL1_euGWONVNnyFR_FiFkZJebIh0WVNwx0_PlBZPzvV_Ll4S2e6JDHIlOA
Accept-Encoding: gzip
Authorization: <Not Logged>
Content-Range: bytes */0
User-Agent: GHFS/hadoop3-2.2.2-dataproc zone/us-central1-c Google-HTTP-Java-Client/1.39.0 (gzip)
Content-Type: application/octet-stream
Content-Length: 0

Oct 26, 2021 5:42:51 AM com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.HttpRequest execute
CONFIG: curl -v --compressed -X PUT -H 'Accept-Encoding: gzip' -H 'Authorization: <Not Logged>' -H 'Content-Range: bytes */0' -H 'User-Agent: GHFS/hadoop3-2.2.2-dataproc zone/us-central1-c Google-HTTP-Java-Client/1.39.0 (gzip)' -H 'Content-Type: application/octet-stream' -d '@-' -- 'https://storage.googleapis.com/upload/storage/v1/b/<BUCKET>/o?ifGenerationMatch=0&name=test-empty-04._COPYING_&uploadType=resumable&upload_id=ADPycdtrIid39eNFjGnt570wYOCu3aCCy872EmJISL1_euGWONVNnyFR_FiFkZJebIh0WVNwx0_PlBZPzvV_Ll4S2e6JDHIlOA' << $$$
```

#### External references such as API reference guides

https://cloud.google.com/storage/docs/resumable-uploads

#### Any additional information below

Seems like this bug caused by this line of code: https://github.com/googleapis/google-api-java-client/blob/f5ea30eb751519392c8c48038baef12331fd8ce4/google-api-client/src/main/java/com/google/api/client/googleapis/media/MediaHttpUploader.java#L363

**Comment by lesv** [comment]
@frankyn Can you get someone to look at this - apologies it's OSLO.

**Comment by lesv** [comment]
Appears to be related to (internal http://b/204369844)

**Comment by lesv** [comment]
also (internal http://b/202332963#comment46)

**Comment by frankyn** [comment]
We've been looking at this with the GCS team internally along with @BenWhitehead. The GCS team is working on a fix with the GFE team to correctly respond with custom hostname supplied when creating a resumable upload. Right now the Java client expects the Location header to have the correct URI to send data to: https://github.com/googleapis/google-api-java-client/blob/main/google-api-client/src/main/java/com/google/api/client/googleapis/media/MediaHttpUploader.java#L363

We could make this change client-side but this should be on the server side to fix per resumable uploads https://cloud.google.com/storage/docs/resumable-uploads the response header Location is where PUT's should be sent to. 

@medb do you still think this change should be made?

**Comment by BenWhitehead** [comment]
One thing to be very clear about, making this change client side will mean that the client does not properly implement handling of the `Location` header according to HTTP expectations. When a fully qualified Location is provided a client is expected to respect that `Location` without any modification or relative resolution

**Comment by BenWhitehead** [comment]
Downgrading to p2 since the backend is investigating the server side fix.

**Comment by medb** [comment]
@frankyn agree, it's proper to fix this on backend, but it could be goo to keep this issue open until its fixed on backed for public tracking purposes.
