### ISSUE TITLE
Google Indexing API request batch In Java (Working Code which is not deprecated as of now)

### ISSUE THREAD

**Issue by jmohammadmirza** [googleapis/google-api-java-client#2015]
Hi Google,

I am trying to upgrade our java code from  the existing Google Indexing API(Single call) to Batch Request API to reduce the HTTP calls.

I went through [google official](https://googleapis.github.io/google-api-java-client/batching.html)  sample  code which is completely misleading.

I can see an old   [Q and A](https://support.google.com/webmasters/forum/AAAA2Jdx3sUL6yVB7iq1os/?hl=en&gpf=%23!topic%2Fwebmasters%2FL6yVB7iq1os%3Bcontext-place%3Dtopicsearch%2Findexing%2420api%2420request%2420batch)  from 2018 , not  sure if this has updated version and it looks deprecated.

Need some sample Java code for using the latest version of Google Indexing Batch API with working examples(for Job postings ).

I have all service accounts and set up with me for doing the postings.

**Comment by suztomo** [comment]
Right, the document may be outdated.

Would you share your code that didn't work?
And error message you observed?

**Comment by jmohammadmirza** [comment]
`

public GenericRes<?> postBatchJobToGoogle(List<JobPostingReq> jobPostingBatch) {
		String result = "";
		String serviceAccountEmail = "";
		try {

			HttpTransport httpTransport = GoogleNetHttpTransport.newTrustedTransport();
			String scopes = "https://www.googleapis.com/auth/indexing";
			String endPoint = "https://indexing.googleapis.com/v3/urlNotifications:publish";
			String batchEndpoint="https://indexing.googleapis.com/batch";
			
			
			InputStream in = null;
			String jsonContents = null;
			List<String> content = JobPostingUtils.preparePostJson(AppConstants.URL_UPDATED,urlsList);
			

			/*
			 * if(!NullUtils.isValid(jbPstDtls.getEmployerId())){
			 * log.error("Error :EmployerId Required"); return error("EmployerId Required");
			 * }
			 */
			Document serviceAccountJson = resolveServiceAccount("googelAccount");
			if(serviceAccountJson==null){
				log.error("Error :Posting permission error");
				return error("Posting permission error");
			}
			jsonContents = serviceAccountJson.getString("jsonContents");
		
			in = new ByteArrayInputStream(jsonContents.getBytes());
			 
			
			GoogleCredentials credentials = GoogleCredentials.fromStream(in).createScoped(Collections.singleton(scopes));
			HttpRequestInitializer requestInitializer = new HttpCredentialsAdapter(credentials); 
			
			
			GenericUrl genericUrl = new GenericUrl(batchEndpoint);
	JsonBatchCallback<PublishUrlNotificationResponse> callback = new JsonBatchCallback<PublishUrlNotificationResponse>() {

        public void onSuccess(PublishUrlNotificationResponse res, HttpHeaders responseHeaders) {
            try {
                System.out.println(res.toPrettyString());
            } catch (IOException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }

        public void onFailure(GoogleJsonError e, HttpHeaders responseHeaders) {
            System.out.println("Error Message: " + e.getMessage());
        }
    };

    IndexingRequestInitializer iri = new IndexingRequestInitializer();
    AbstractGoogleClient client;// Not Sure How to initialize
    BatchRequest batch = client.batch(requestInitializer);
    batch.setBatchUrl(new GenericUrl("https://indexing.googleapis.com/batch"));

    for (String url : 

public GenericRes<?> postBatchJobToGoogle(List<JobPostingReq> jobPostingBatch) {
		String result = "";
		String serviceAccountEmail = "";
		try {

			HttpTransport httpTransport = GoogleNetHttpTransport.newTrustedTransport();
			String scopes = "https://www.googleapis.com/auth/indexing";
			String endPoint = "https://indexing.googleapis.com/v3/urlNotifications:publish";
			String batchEndpoint="https://indexing.googleapis.com/batch";
			
			
			InputStream in = null;
			String jsonContents = null;
			String content = JobPostingUtils.preparePostJson(AppConstants.URL_UPDATED,"jbPstDtls.getSubmittedUrl()");
			

			/*
			 * if(!NullUtils.isValid(jbPstDtls.getEmployerId())){
			 * log.error("Error :EmployerId Required"); return error("EmployerId Required");
			 * }
			 */
			Document serviceAccountJson = resolveServiceAccount("jbPstDtls.getProjectId()");
			if(serviceAccountJson==null){
				log.error("Error :Posting permission error");
				return error("Posting permission error");
			}
			jsonContents = serviceAccountJson.getString("jsonContents");
			//jbPstDtls.setProjectId(serviceAccountJson.getString("employerId"));
			in = new ByteArrayInputStream(jsonContents.getBytes());
			 
			
			GoogleCredentials credentials = GoogleCredentials.fromStream(in).createScoped(Collections.singleton(scopes));
			HttpRequestInitializer requestInitializer = new HttpCredentialsAdapter(credentials); 
			
			
			GenericUrl genericUrl = new GenericUrl(batchEndpoint);
	JsonBatchCallback<PublishUrlNotificationResponse> callback = new JsonBatchCallback<PublishUrlNotificationResponse>() {

        public void onSuccess(PublishUrlNotificationResponse res, HttpHeaders responseHeaders) {
            try {
                System.out.println(res.toPrettyString());
            } catch (IOException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }

        public void onFailure(GoogleJsonError e, HttpHeaders responseHeaders) {
            System.out.println("Error Message: " + e.getMessage());
        }
    };

    IndexingRequestInitializer iri = new IndexingRequestInitializer();
    AbstractGoogleClient client;
    BatchRequest batch = client.batch(requestInitializer);
    batch.setBatchUrl(new GenericUrl("https://indexing.googleapis.com/batch"));

    for (JobPostingReq url : jobPostingBatch) {
        UrlNotification unf = new UrlNotification();// UrlNotification import issue compiler error
        unf.setUrl(url.getjobURL);
        unf.setType("URL_UPDATED");
        client.urlNotifications().publish(unf).queue(batch, callback);
    }

    batch.execute();

    }
			
				
		} catch (Exception e) {
			result = "Error : " + e.getMessage();
			
			//update logs based on each url in mongo collection
			e.printStackTrace();
			return  error(result) ;
		}
		
		
		return  success(result) ;
	}

**Comment by jmohammadmirza** [comment]
Code is giving compiler error on` UrlNotification `.

Not sure on how to initialize got using this link 
`AbstractGoogleClient client;`

**Comment by jmohammadmirza** [comment]
![image](https://user-images.githubusercontent.com/8312219/159659516-27e01330-c10c-4cbd-88cc-2b73c4056e2f.png)
`URLNotification `issue.

regarding the `AbstractGoogleClient `do I have use Books cannot I use some Custom Pojo from my end like `Jobs`

**Comment by suztomo** [comment]
Where did you get the code snippet of `UrlNotification`? I didn't find the document you referenced (https://googleapis.github.io/google-api-java-client/batching.html).

> Custom Pojo

No, you cannot use a custom pojo. It has to be a child class of AbstractGoogleClient.

**Comment by jmohammadmirza** [comment]
`UrlNotification`  This code I got from [stackoverflow](https://stackoverflow.com/questions/54285181/google-indexing-api-request-batch-in-java)

```
   for (String url : urls) {
        UrlNotification unf = new UrlNotification();
        unf.setUrl(url);
        unf.setType("URL_UPDATED");
        client.urlNotifications().publish(unf).queue(batch, callback);
    }
```

**Comment by suztomo** [comment]
I'm afraid that I cannot help the problem in the code you get from Stackoverflow.
