### ISSUE TITLE
What does the file src/main/resources/com/google/api/client/googleapis/google.jks store? Private key or public key? Can user konw the password of the file ?

### ISSUE THREAD

**Issue by BadTrasher** [googleapis/google-api-java-client#2027]
Thanks for stopping by to let us know something could be better!

Please be sure to include as much information as possible:

#### Environment details

- OS:
- Java version:
- google-api-java-client version:

#### Steps to reproduce

1. ?
2. ?

#### Stacktrace

```
Any relevant stacktrace here.
```

#### External references such as API reference guides used

- ?

#### Any additional information below

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by chingor13** [comment]
This stores official Google public keys. It's used to verify that a connection is actually going directly to Google and not being MITM attacked. It's used if you call [`newTrustedTransport()`](https://github.com/googleapis/google-api-java-client/blob/2d25655b94dc1ae93b5c3a97046daf6a35a9923b/google-api-client/src/main/java/com/google/api/client/googleapis/javanet/GoogleNetHttpTransport.java#L71) and the passcode is hardcoded [`notasecret`](https://github.com/googleapis/google-api-java-client/blob/2d25655b94dc1ae93b5c3a97046daf6a35a9923b/google-api-client/src/main/java/com/google/api/client/googleapis/GoogleUtils.java#L86)
