### ISSUE TITLE
storage: HTTP 416 on GET request of 0 length file

### ISSUE THREAD

**Issue by weichungwen** [googleapis/google-api-java-client#2076]
#### Environment details

  - Programming language: Java
  - OS: Debian 11
  - Language runtime version: OpenJDK 17
  - Package version: google-api-services-storage v1-rev20211018-1.32.1

#### Steps to reproduce

  1. Create an empty file on Cloud Storage
  2. Create a service account and download its JSON key
  3. Decompress the attached [my-app.tar.gz](https://github.com/googleapis/google-api-java-client-services/files/7500741/my-app.tar.gz) and substitute constants `PRIVATE_KEY`, `SERVICE_ACCOUNT`, `GCS_BUCKET` and `GCS_OBJECT` in `src/main/java/com/example/App.java`
  4. Compile with `mvn compile` then run with `mvn exec:java -Dexec.mainClass=com.example.App -Djava.util.logging.config.file=logging.properties`

#### Similar issue

It seems `Storage.Objects.Get.executeMediaAndDownloadTo()` adds `Range: bytes=0-33554431` which leads to  `416 Requested range not satisfiable`. A similar report can be found in [golang client library](https://github.com/googleapis/google-cloud-go/issues/242#issuecomment-211743914).

**Comment by BenWhitehead** [comment]
"internal"note: This is not unique to Storage, it applies to the api client which in turn is used by all apiary generated clients.

**Comment by blakeli0** [comment]
Closing since this is a rare use case that it only happens with empty files.
