### ISSUE TITLE
Auth: Duplicate signature verification check in GoogleIdTokenVerifier

### ISSUE THREAD

**Issue by alexmitic** [googleapis/google-api-java-client#2077]
#### Environment details

1. OS type and version: N/A
2. Java version: N/A
3.  version(s): [google-api-java-client v1.34.1](https://github.com/googleapis/google-api-java-client/releases/tag/v1.34.1) & [google-oauth-java-client v1.33.3](https://github.com/googleapis/google-oauth-java-client/releases/tag/v1.33.3)

#### Steps to reproduce

The latest release of `google-oauth-java-client` added a [signature verification check to IdTokenVerifier.verify](https://github.com/googleapis/google-oauth-java-client/pull/861/files#diff-614b71029b58782f8684645ff56c443eac1ab67b0f6736911ae100d7e3971f8f). In `google-api-java-client`, `GoogleIdTokenVerifier` makes a [call to super.verify](https://github.com/googleapis/google-api-java-client/blob/2b1558d07d1f79939def761911d1fbdb6fb31257/google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleIdTokenVerifier.java#L165) which will perform a [signature check](https://github.com/googleapis/google-oauth-java-client/blob/c1b1468807b97472665c0e218ffcf6955ec57190/google-oauth-client/src/main/java/com/google/api/client/auth/openidconnect/IdTokenVerifier.java#L246). After that GoogleIdTokenVerifier then performs its [own signature check](https://github.com/googleapis/google-api-java-client/blob/2b1558d07d1f79939def761911d1fbdb6fb31257/google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleIdTokenVerifier.java#L169-L173). 

This look like the signature check is effectively being duplicated?

**Comment by TimurSadykov** [comment]
This is going to be fixed along with the https://github.com/googleapis/google-oauth-java-client/issues/891
