### ISSUE TITLE
Which API can be used to fetch the apk size data?

### ISSUE THREAD

**Issue by Apochens** [googleapis/google-api-java-client#2125]
I want to use the Google API to get **the apk size data**, but it seems that the **Google Play Developer API** and the **Google Play Developer Reporting API** both cannot reach that data. So which API can I use to get that data?

**Comment by meltsufin** [comment]
It's not really a question about the Java client for the API, but I think one way would be to download the APK and just check the size of the file. See: https://developers.google.com/android-publisher/download-apks
