### ISSUE TITLE
Gmail API Cyrillic Support

### ISSUE THREAD

**Issue by olegkdev** [googleapis/google-api-java-client#2132]
I'm working with the example SendMessageWithAttachment.java. It works fine with English email body. However Cyrillic letters (Ukrainian) work only in the email's title and attachments file names. Body text was not recognized in Cyrillic.
Example without attachments and without MIME works good with Cyrillic text.
So, is there any way to send non-English letters with Gmail API with attachments and MIME?

Example without attachments (without MIME) https://github.com/googleworkspace/java-samples/blob/main/gmail/snippets/src/main/java/SendMessage.java

Example with attachments https://github.com/googleworkspace/java-samples/blob/main/gmail/snippets/src/main/java/SendMessageWithAttachment.java

**Comment by lqiu96** [comment]
Do you have a screenshot of the differences you're seeing? I'm a bit confused by `body text not recognized in Cyrillic`.

I'll pull down the examples when I get a chance.

**Comment by olegkdev** [comment]
Screenshots https://github.com/JavaCodeSamples/TestGmailAPI/tree/main/docs

Code https://github.com/JavaCodeSamples/TestGmailAPI/blob/main/src/main/java/org/example/GmailQuickstart.java

**Comment by lqiu96** [comment]
Apologies for the delay. Can you try with `mimeBodyPart.setContent(bodyText, "text/plain;charset=utf-8");`? 

I've tried locally and it seems to recognize Cyrillic in the body.

> The default character set, which must be assumed in the absence of a charset parameter, is US-ASCII.
From: https://www.rfc-editor.org/rfc/rfc2046

**Comment by olegkdev** [comment]
Yes, this works with Cyrillic `mimeBodyPart.setContent(bodyText, "text/plain;charset=utf-8");` Thank you for help and explanation
