### ISSUE TITLE
java.net.SocketTimeoutException with java-bigquery client library

### ISSUE THREAD

**Issue by prash-mi** [googleapis/google-api-java-client#2135]
We recently encountered `java.net.SocketTimeoutException` with java-bigquery after we increased the server side timeout for one of the BigQuery REST services.  This causes the server delay the response for long running queries (basically it waits and polls on the server side, but from the client API point of view we may not get the HTTP response for the mentioned amount of time, which we defines as 60000 ms, but it could be quite a longer time too)
Related Bug: https://github.com/googleapis/java-bigquery/issues/2248

Is there a way we can increase the transport layer timeout? Or would you suggest any other settings/configuration to be used when the REST API is expected to take a long time to return? Please note that the above mentioned issue is an intermittent one.

**Comment by diego92sigma6** [comment]
Socket timeout was increased to 10s in [PR 2260 (merged)](https://github.com/googleapis/java-bigquery/pull/2260). Closing as solved.
