### ISSUE TITLE
API cloud-identity.devices.readonly error 403: "The caller does not have permission"

### ISSUE THREAD

**Issue by ikozl** [googleapis/google-api-java-client#2139]
The access token then doesn't seem to have the require scope/permissions and a call to https://cloudidentity.googleapis.com/v1/devices results in a 403 forbidden
{
    "error": {
        "code": 403,
        "message": "The caller does not have permission",
        "status": "PERMISSION_DENIED"
    }
}
Required one of the following OAuth scopes, seems to be not enough:
https://www.googleapis.com/auth/cloud-identity.devices.readonly
https://www.googleapis.com/auth/cloud-identity.devices
https://www.googleapis.com/auth/cloud-identity

**Comment by lqiu96** [comment]
Could you give me some more context as to you're trying to do/ how you're getting this error? Do you have a link to a code sample, tutorial, or repo that I could follow and try to reproduce this error? Thanks!

**Comment by ikozl** [comment]
I try to call using: 
`
function getTestCall(){

const testCall = {
  url: 'https://cloudidentity.googleapis.com/v1/devices',
  method : "GET"
} 

try {
      var response = UrlFetchApp.fetch(testCall.url, {
        method: testCall.method,
        muteHttpExceptions: true,
        contentType: "application/json",
        headers: {
          Authorization: "Bearer " + getAccessToken()
        }
      });
      [console.info](http://console.info/)(response.getContentText(), response.getResponseCode());
    } catch (e) {
      console.error(e);
    }
}
`

**Comment by lqiu96** [comment]
I'm going to have to guess something may be wrong with your accessToken (not pulling in the correct scopes that you have access to). I'm not sure how you're getting the token/ I don't see how `getAccessToken()` is implemented.

Are you using either of these libraries to facilitate getting the token or making the call? 
https://github.com/googleapis/google-auth-library-nodejs or https://github.com/googleapis/google-api-nodejs-client

Also, FYI - This is the java-client libraries. I'm not too familiar with nodejs/ javascript environment, so you may find better support in those repos.
