### ISSUE TITLE
Initializing Google Drive API using builder giving Exception

### ISSUE THREAD

**Issue by tusharaina** [googleapis/google-api-java-client#2159]
#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version: Android OS 10/11/12/13
3. Java version: depending on Android devices
4. Version(s): com.google.api-client:google-api-client:1.31.1

#### Steps to reproduce
It is not reproducible at our end and getting reported on firebase.

#### Code example

```java
Drive.Builder(netHttpTransport, jacksonFactory, setHttpTimeout(accountCredential)).build()
```

#### Stack trace
```
Caused by java.lang.IllegalStateException: No successful match so far
       at java.util.regex.Matcher.ensureMatch(Matcher.java:1189)
       at java.util.regex.Matcher.group(Matcher.java:456)
       at com.google.api.client.googleapis.GoogleUtils.<clinit>(GoogleUtils.java:66)
       at com.google.api.services.drive.Drive.<clinit>(Drive.java:44)
       at com.google.api.services.drive.Drive$Builder.build(Drive.java:9813)
```

#### Any additional information below
This is similar to https://github.com/googleapis/google-api-java-client/issues/1451 which is marked closed but is still reproducible on google api client 1.31.1.
Please let me know for any additional details.

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by diegomarquezp** [comment]
Hello.
Could you please provide the Drive library version you are using?
Also, if you have premium support, please contact Support for a faster response time.
Thanks!

**Comment by lqiu96** [comment]
@tusharaina Hi, are you still seeing this error? Do you have a sample repo for us to try and reproduce?

**Comment by tusharaina** [comment]
@diegomarquezp drive version which we are using is `com.google.apis:google-api-services-drive:v3-rev20191108-1.30.3`

**Comment by tusharaina** [comment]
@diegomarquezp / @lqiu96 any update on this issue as we are seen many instances of this issue on our play console.

**Comment by lqiu96** [comment]
@tusharaina Apologies, I missed your previous message. I'll take a look at the Drive library and play around with it, but without a repro I'm not sure if I can replicate.

> Currently this is not reproducible in house and we are getting this on firebase.

Have you reached out the Firebase regarding the error message? It might be possible that there is a more detailed error message in the console or logs.

**Comment by tusharaina** [comment]
@lqiu96 below are the logs/stacktrace from firebase::
`Caused by java.lang.IllegalStateException: No successful match so far
       at java.util.regex.Matcher.ensureMatch(Matcher.java:1189)
       at java.util.regex.Matcher.group(Matcher.java:456)
       at com.google.api.client.googleapis.GoogleUtils.<clinit>(GoogleUtils.java:66)
       at com.google.api.services.drive.Drive.<clinit>(Drive.java:44)
       at com.google.api.services.drive.Drive$Builder.build(Drive.java:9813)
       at com.adobe.libs.connectors.googleDrive.CNGoogleDriveConnectorAccount.makeGoogleClient(CNGoogleDriveConnectorAccount.kt:60)
       at com.adobe.libs.connectors.googleDrive.CNGoogleDriveConnectorAccount.<init>(CNGoogleDriveConnectorAccount.kt:320)
       at com.adobe.libs.connectors.googleDrive.CNGoogleDriveConnector.createConnectorAccount(CNGoogleDriveConnector.kt:53)
       at com.adobe.libs.connectors.utils.CNConnectorUtils$addConnectorAccount$2.invokeSuspend(CNConnectorUtils.kt:127)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)`
       
We were able able to reproduce this on OS 13 device wherein when we try to login in via Drive SDK using new account which is not present on the device from the account chooser screen.

**Comment by lqiu96** [comment]
I've been playing around with the Drive repo + api-client, but haven't been able to replicate the `Caused by java.lang.IllegalStateException: No successful match so far at java.util.regex.Matcher.ensureMatch(Matcher.java:1189)` error.  Pulling in your versions of api-client and Drive still doesn't produce this error (I'm able to get a valid response from the Drive API). Debugging through the invocations show the versions are being able to parsed correctly.

I'll create an Android sample and see if I can produce it there. Let me know if there is anything else that'll help me produce this error. Thanks!

**Comment by tusharaina** [comment]
@lqiu96 could you please share any update on this issue ?

**Comment by meltsufin** [comment]
@tusharaina The version of the library you're using seems very old. Can you try latest?

**Comment by lqiu96** [comment]
@tusharaina I haven't been able to reproduce this issue on my computer. Can you share a list of your dependencies or your `build.gradle` file? Also you can try @meltsufin 's suggestion of trying the latest drive version: 

Checking maven central, it looks to be:
```
        <dependency>
            <groupId>com.google.apis</groupId>
            <artifactId>google-api-services-drive</artifactId>
            <version>v3-rev20221219-2.0.0</version>
        </dependency>
```

**Comment by tusharaina** [comment]
@lqiu96 / @meltsufin we are trying to update the library to latest version.
Wanted to share an update, this is happening for our users who have just installed your app from playstore and we use dynamic feature splits? (also known by various names like Play Feature Delivery: https://developer.android.com/guide/playcore/feature-delivery ). 
Recently we faced a crash in our webview due to app splits wherein when webView is first loaded into your app process, your app is automatically granted the ability to see the WebView implementation package so that it can use it. However, this automatic grant is temporary, and is removed if your app is updated. Unfortunately, Android also treats dynamic split installations as app updates - they just use a special flag that *prevents* the app from being killed automatically. The package visibility implementation doesn't take this flag into account, and removes the temporary visibility grant anyway, revoking your app's ability to see WebView's package. Then, when we try to look up the service definitions in the WebView package, we can't find them and it crashes.
Could this be happening in this case and there might be some changes happened in OS 13 due to which no matches is found for the service and causing app to crash due to the same exception and breaking our workflow.
In our reproduced steps also, we are facing this crash while installing the app from the play store for the first time and trying to login into Drive. And this crash doesn't happen when we try to login to GDrive/Gmail on relaunching the app.

**Comment by meltsufin** [comment]
You need `google-api-client` dependency in your classpath for `GoogleUtils`.

**Comment by tusharaina** [comment]
@meltsufin we have these dependencies on our app for quite some time in production up until recently we have started seeing this crash only on Android OS:13 devices where it is unable to get this.
And I could see this dependency gets added transitively from `com.google.apis:google-api-services-drive` and `com.google.apis:google-api-services-gmail` dependency in the app. And we are facing this issue only on first launch of the app and not on subsequent launches, so could something might be happening on fresh launch after install on OS:13  ?

**Comment by meltsufin** [comment]
Unfortunately, we cannot help with Android-specific issues. You might want to seek support from the Android devs.

**Comment by tusharaina** [comment]
@meltsufin where do I need to post this for checking this issue ? I thought this was the channel to post these queries.

**Comment by meltsufin** [comment]
Maybe start here: https://developer.android.com/support.
