### ISSUE TITLE
Example for use with API key No OAUTH

### ISSUE THREAD

**Issue by LindaLawton** [googleapis/google-api-java-client#2221]
All of your samples are for use with Oauth2 even your example for the google books api requires Oauth2.

[oauth-2.0.md](https://github.com/googleapis/google-api-java-client/blob/f4068b68a5db46086fd1db60f6dce91e0dc263c7/docs/oauth-2.0.md)

Do you have an example for using a public api key.  I don't need auth what i am trying to access is public data.

**Comment by emmileaf** [comment]
In general OAuth is recommended to authenticate your requests, and you can find more instructions on configuring credentials [here](https://developers.google.com/api-client-library/java/google-api-java-client/oauth2). 

Support for usage without OAuth is likely specific to the API - could you help me understand if you are looking to use the Books API in particular (or just pointing to it as an example), and whether you are running into any specific blockers for setting up authentication?

**Comment by meltsufin** [comment]
@TimurSadykov Do you have more info on API Key support in Java auth?

@LindaLawton I see that the public documentation states that API Key support is language-specific, and there's only an example for Python.
https://cloud.google.com/docs/authentication/api-keys#using-with-client-libs

**Comment by TimurSadykov** [comment]
There is no 1st-class support yet. However, there is usually a way to pass an API key. [Example](https://github.com/arithmetic1728/java-language/blob/api_key/google-cloud-language/src/test/java/com/google/cloud/language/v1/SampleTest.java#L43-L54) for GAPIC clients.

**Comment by emmileaf** [comment]
@LindaLawton Could you try if something like this works for your API key usage pattern?   

Compared to the OAuth sample for Books API: 
```
Books books =
    new Books.Builder(
            GoogleNetHttpTransport.newTrustedTransport(),
            GsonFactory.getDefaultInstance(),
            new HttpCredentialsAdapter(credentials))
        .setApplicationName("BooksExample/1.0")
        .build();
```

Try passing in null for the `HttpRequestInitializer` argument, but explicitly set a `GoogleClientRequestInitializer` with the API key:
```
Books books =
    new Books.Builder(
            GoogleNetHttpTransport.newTrustedTransport(),
            GsonFactory.getDefaultInstance(),
            null)
        .setApplicationName("BooksExample/1.0")
        .setGoogleClientRequestInitializer(new BooksRequestInitializer(API_KEY))
        .build();
```

**Comment by alicejli** [comment]
Closing due to lack of response. Please re-open or file a new issue if still relevant.
