### ISSUE TITLE
Support jakarta.servlet naming over javax.servlet

### ISSUE THREAD

**Issue by Edwardiv1** [googleapis/google-api-java-client#2260]
I'd like to upgrade to newer versions of JakartaEE/JavaEE, but the package names have changed from javax.servlet to jakarta.servlet, so the Google Client SDK won't run (class not found errors).

This request is for the new Jakarta package names to be supported.

**Comment by ludoch** [comment]
By the way, Google App Engine Java21 now supports the Jakarta names. See https://twitter.com/ludoch/status/1732519005288796264

**Comment by ragnor** [comment]
When support of jakarta can be expected? It blocks migration from Spring Boot 2.x to 3.x

**Comment by Edwardiv1** [comment]
Does anyone know of a workaround for this issue? Doesn't look like it's high on the priority list.

**Comment by suztomo** [comment]
@Edwardiv1 I ran sample project in Jakarta 10 EE and it just worked fine to use google-api-java-client. Would you share a simple Servlet example that fails due to ClassNotFound error?

**Comment by ludoch** [comment]
Every where you see javax.servlet.* in https://github.com/search?q=repo%3Agoogleapis%2Fgoogle-api-java-client%20javax.servlet&type=code this library will not work on Jakarta web servers.

**Comment by ludoch** [comment]
For example, try to use google-api-client-servlet/src/main/java/com/google/api/client/googleapis/extensions/servlet/notifications/WebhookUtils.java with your Jarkata servlet request object and you'll see a ClassNotFound at runtime ( Java EE servers provide at runtime the servlet APIs, they should not be bundled with your app)

**Comment by suztomo** [comment]
@Edwardiv1 @ragnor Are you using NotificationServlet or WebhookUtils that appear in the search query ludo@'s comment?

**Comment by ragnor** [comment]
Yes, I'm using WebhookUtils class.

czw., 9 maj 2024, 02:18 użytkownik Tomo Suzuki ***@***.***>
napisał:

**Comment by suztomo** [comment]
@ragnor Thank you. Pardon my ignorance, but is there any document that recommends you to use the WebhookUtils class? Understanding usages helps prioritization.

**Comment by Edwardiv1** [comment]
I'm using Google Calendar Java SDK. The part the uses servlets is referenced in the following link:
https://developers.google.com/api-client-library/java/google-api-java-client/oauth2#web_server_applications

**Comment by suztomo** [comment]
@Edwardiv1 Thank you. Yes, these servlet classes are in a different repository. Follow https://github.com/googleapis/google-oauth-java-client/issues/1112.

**Comment by Edwardiv1** [comment]
I see. Thanks. That other link was filed just last week - I suppose that means they might get a response next year sometime.

**Comment by suztomo** [comment]
@Edwardiv1 We released google-oauth-client-servlet 1.36.0. Would you try the new classes in the new "jakarta" package?
See https://github.com/googleapis/google-oauth-java-client/releases/tag/v1.36.0 for the class names.

**Comment by suztomo** [comment]
@ragnor Do you use WebhookUtils for Google Drive? https://developers.google.com/drive/api/guides/push

**Comment by ragnor** [comment]
Yes, I do. It is a legacy code that I've inherited. Is there any other
recommended way of consuming google drive notifications in Java?

**Comment by suztomo** [comment]
I just wanted to confirm the use cases. I'll get back to you soon.

**Comment by ragnor** [comment]
It is the only class from the lib that I use that has javax imports. Simple
copy of the class where all javax are replaced by jakarta have unblocked
migration to Spring Boot 3.x.
Still at some point I hope I will remove this workaround and use only
official classes from the lib.

pon., 13 maj 2024, 17:04 użytkownik Tomo Suzuki ***@***.***>
napisał:
