### ISSUE TITLE
Create sample showing how to authorize Admin SDK Directory service with Service Account and credentials JSON

### ISSUE THREAD

**Issue by ym-herby** [googleapis/google-api-java-client#2264]
All of the examples I've found so far don't quite address this scenario. I"ve cobbled together something but I can't quite figure out why I'm getting this very opaque 400 Bad Request error.

There seem to be multiple ways to obtain a credential but it's not clear which class should be used: Credential, GoogleCredentials, etc. Some are deprecated.

I'm new to GCP so I'm probably missing something very obvious but basically all I want to do is use the credentials.json file to authenticate to Admin SDK Directory Service and look up a user in the directory.  This should be really simple but the documentation and various workarounds on SO and elsewhere have only created more confusion.

**Comment by mpeddada1** [comment]
@ym-herby You may find the [oauth-2.md ](https://github.com/googleapis/google-api-java-client/blob/f4068b68a5db46086fd1db60f6dce91e0dc263c7/docs/oauth-2.0.md#credentials)documentation page to be helpful in getting started. It goes into detail on how each type of authentication flow can be implemented. Specifically the ["Service Accounts"](https://github.com/googleapis/google-api-java-client/blob/f4068b68a5db46086fd1db60f6dce91e0dc263c7/docs/oauth-2.0.md#service-accounts) section.

**Comment by blakeli0** [comment]
@ym-herby Please check if your interested service has a newer version of client libraries in [google-cloud-java](https://github.com/googleapis/google-cloud-java), and you might be able find more samples in [java-docs-samples](https://github.com/GoogleCloudPlatform/java-docs-samples) or https://cloud.google.com/docs/samples.
