### ISSUE TITLE
Compliance issue: Sun's licensing of servlet-api

### ISSUE THREAD

**Issue by wojteo** [googleapis/google-api-java-client#2277]
https://github.com/googleapis/google-api-java-client/blob/3cb09eb2dd5ed5f3eb5b9d18b7e4413d2f3634f1/pom.xml#L512
If you look at [the sources](https://repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5-sources.jar) of servlet-api dependency in version 2.5, you can find the following statement in the package.html file(s):
>  Copyright 2001 Sun Microsystems, Inc. All Rights Reserved.
>
> This software is the proprietary information of Sun Microsystems, Inc.  
> Use is subject to license terms.

What exactly are these license terms?
How does google address this licensing issue? 
Is there any agreement with Oracle that users of google-api-java-client can use that dependency on any specific terms?

Or maybe it's possible to migrate to [javax.servlet/javax.servlet-api](https://mvnrepository.com/artifact/javax.servlet/javax.servlet-api) which modified that statement to be in line with  Oracle's `CDDL+GPL_1_1 w/CPE` combo

Optionally rolling back to [2.4](https://mvnrepository.com/artifact/javax.servlet/servlet-api/2.4) would seem to solve the issue as well, as there is no such statement there

**Comment by meltsufin** [comment]
The library appears to be covered by CDDL as seen in the `.java` source files for the package. The vague language in the `package.html` file isn't sufficient to call that question. However, feel free to seek clarification on your own from authors of the library.
