### ISSUE TITLE
Issue with google-api-client

### ISSUE THREAD

**Issue by alekhyaga** [googleapis/google-api-java-client#2336]
Hi team,
Currently, I'm using google api service compute in our project and in the run time it is using google-api-client recent version 2.2.0. I'm receiving below mentioned error when I execute my code. 
`You are currently running with version 2.2.0 of google-api-client. You need at least version 1.31.1 of google-api-client to run version 1.32.1 of the Compute Engine API library.`
Gradle package details:
`compile group: 'com.google.apis', name: 'google-api-services-compute', version: 'v1-rev20211130-1.32.1'`

Also, one of support team member suggested me to use "google-api-client 1.31.5" & "google-api-services-compute v1-rev20210603-1.32.1" as these are stable versions. But, I noticed "google-api-client 1.31.5" has security vulnerabilities from dependencies "google-oauth-client". 
https://mvnrepository.com/artifact/com.google.api-client/google-api-client/1.31.5
So, can someone please suggest what is the stable version that I could use to resolve this?

Thank you,
Alekhya

**Comment by diegomarquezp** [comment]
Hi @alekhyaga, thanks for bringing this up. Would you mind sharing the involved section of your pom?
The suggested stable version of `compute/v1` is [here](https://github.com/googleapis/google-api-java-client-services/tree/main/clients/google-api-services-compute/v1/2.0.0) (as opposed to `20210603`): 

```
<dependency>
      <groupId>com.google.apis</groupId>
      <artifactId>google-api-services-compute</artifactId>
      <version>v1-rev20230606-2.0.0</version>
    </dependency>
```

**Comment by alekhyaga** [comment]
Hi @diegomarquezp, we are using build.gradle file. Here is the package details:
Before:
`compile group: 'com.google.apis', name: 'google-api-services-compute', version: 'v1-rev20211130-1.32.1'`
After updating to the suggested package it's working.
`compile group: 'com.google.apis', name: 'google-api-services-compute', version: 'v1-rev20230606-2.0.0'`

Thank you for the quick response.

Best Regards,
Alekhya
