### ISSUE TITLE
Unit test capabilities?

### ISSUE THREAD

**Issue by ygini** [googleapis/google-api-java-client#2374]
**Is your feature request related to a problem? Please describe.**
Our test coverage is currently blind when working with the Google API, we can test up to the call to Google SDK, but we cannot test that the Google SDK behave as expected with the data we send to.

**Describe the solution you'd like**
Having a mock / test capabilities built into the framework to allow our test units to works without the real Google API, to confirm that everything works

**Describe alternatives you've considered**
Writing our test using a test Google Cloud Project, which is not really helpful as we cannot test on developer workstation and are subject to third party service state (we cannot ensure a clean state or specific state before each run).

**Additional context**
Our current needs are specifically in identity management, usually we works with SCIM that we can test as wanted, but since Google does not support this standard and use custom API, we are limited in our quality process to what the Google SDK here can offer.

**Comment by burkedavison** [comment]
Hey @ygini ,

We do not have any current plans to implement a client-side IAM emulator, but I encourage you to reach out to [Google Cloud customer support](https://cloud.google.com/support/) with your request. Doing so would put this in front of the right people to assist with your immediate needs, and have this request more formally reviewed.
