### ISSUE TITLE
Drive: Missing shortcut details

### ISSUE THREAD

**Issue by loganmzz** [googleapis/google-api-java-client#2415]
#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
2. OS type and version: Ubuntu
3. Java version: Eclipse Temurin 17.0.4
4.  version(s):
  * `google-api-client=2.2.0`
  * `google-api-services-drive=v3-rev20240110-2.0.0`

#### Steps to reproduce

```kotlin
val client = Drive.Builder(
    GoogleNetHttpTransport.newTrustedTransport(),
    GsonFactory.getDefaultInstance(),
    GoogleCredential
        .fromStream(PaySlipService::class.java.getResourceAsStream("/google-credentials.json"))
        .createScoped(listOf(DriveScopes.DRIVE, DriveScopes.DRIVE_FILE))
    )
    .setApplicationName("MyApp")
    .build()

client
    .files()
    .list()
    .setQ("'${Google-Drive-File-Id}' in parents")
    .execute()        
    .files
    .forEach {
        println("\t- name: ${it.name}")
        println("\t  kind: ${it.kind}")
        println("\t  mimeType: ${it.mimeType}")
        println("\t  shortcutDetails.targetId: ${it.shortcutDetails?.targetId}")
        println("\t  shortcutDetails.targetMimeType: ${it.shortcutDetails?.targetMimeType}")
    }
```

#### Code example

See above

#### Stack trace

N/A

#### External references such as API reference guides

- Same issue for Go client: https://github.com/googleapis/google-api-go-client/issues/464
- API Reference - Google Drive - File resource: https://developers.google.com/drive/api/reference/rest/v3/files#File.FIELDS.shortcut_details

#### Any additional information below

N/A

**Comment by blakeli0** [comment]
Hi @loganmzz, can you elaborate on this issue? I do see [shortcutDetails](https://github.com/googleapis/google-api-java-client-services/blob/824d4155ccb9903fc9133078d93db184b02c6a41/clients/google-api-services-drive/v2/2.0.0/com/google/api/services/drive/model/File.java#L504) in the model class.

**Comment by loganmzz** [comment]
Value is null

**Comment by loganmzz** [comment]
Any news ? Or at least a workaround ?

**Comment by suztomo** [comment]
(I didn't get a chance to run the code) The API document (https://developers.google.com/drive/api/reference/rest/v3/files#File.FIELDS.shortcut_details) says:

> Shortcut file details. Only populated for shortcut files, which have the mimeType field set to application/vnd.google-apps.shortcut.

Would you share execution result (this includes the mimeType) and the screenshot showing the file is a shortcut?

**Comment by loganmzz** [comment]
> (I didn't get a chance to run the code) The API document (https://developers.google.com/drive/api/reference/rest/v3/files#File.FIELDS.shortcut_details) says:
> 
> > Shortcut file details. Only populated for shortcut files, which have the mimeType field set to application/vnd.google-apps.shortcut.
> 
> Would you share execution result (this includes the mimeType) and the screenshot showing the file is a shortcut?

Damn. The mimeType is correct, the file id and link matches shortcuts. But info about target file is missing (`null`). 
I have also a client in Python, not checked if it works.

But as stated in my first message, similar issue has been found with Go client.

**Comment by suztomo** [comment]
https://github.com/googleapis/google-api-go-client/issues/464 was when the field was not there. If you see the same problem in Python SDK, then this repository (the Java SDK generation) cannot solve the problem. In that case, would you file an issue in the same manner as https://github.com/googleapis/google-api-go-client/issues/464?

**Comment by loganmzz** [comment]
I'm going to test with Web (JavaScript) & Python clients on next Monday. At least witth former I will see API calls.

**Comment by loganmzz** [comment]
Ok just check wih JS client. Neither `Drive.files.list()` or `Drive.files.get()` give me more details than:

* `kind`
* `id`
* `name`
* `mimeType`

I have to add `fields` parameter `fields=files(*)` /  `fields=files(id,name,mimeType,shortcutDetails)` or `fields=*` / `fields=id,name,mimeType,shortcutDetails` respectively.

So sad, it is not mentionned in API reference ...
