### ISSUE TITLE
The subscriptionsv2 api does not return price and currency?

### ISSUE THREAD

**Issue by hakusai22** [googleapis/google-api-java-client#2500]
The subscriptionsv2 api does not return price and currency?

- https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptionsv2#SubscriptionPurchaseLineItem
<img width="1758" alt="image" src="https://github.com/googleapis/google-api-java-client/assets/58761705/24fc901b-0333-4b16-a314-f5959e172f61">

<img width="1626" alt="image" src="https://github.com/googleapis/google-api-java-client/assets/58761705/bd0ed977-56d6-4503-855e-d383a6411285">

**Comment by JoeWang1127** [comment]
Hi @hakusai22, thanks for the question.

In the second screenshot, the price info (I didn't find these info in the link you mentioned in the question) can be found through [OfferDetails](https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptionsv2#OfferDetails), which contains `basePlanId` and `offerId`.

**Comment by hakusai22** [comment]
> Hi @hakusai22, thanks for the question.
> 
> In the second screenshot, the price info (I didn't find these info in the link you mentioned in the question) can be found through [OfferDetails](https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptionsv2#OfferDetails), which contains `basePlanId` and `offerId`.

Thanks for your answer. I got the basePlanId but I couldn't find the API to get the baseplan.

**Comment by JoeWang1127** [comment]
I searched the API page and [basePlans.offers](https://developers.google.com/android-publisher/api-ref/rest/v3/monetization.subscriptions.basePlans.offers) seems containing the price info (https://developers.google.com/android-publisher/api-ref/rest/v3/monetization.subscriptions.basePlans.offers#SubscriptionOffer to be specific).

**Comment by hakusai22** [comment]
> I searched the API page and [basePlans.offers](https://developers.google.com/android-publisher/api-ref/rest/v3/monetization.subscriptions.basePlans.offers) seems containing the price info (https://developers.google.com/android-publisher/api-ref/rest/v3/monetization.subscriptions.basePlans.offers#SubscriptionOffer to be specific).

Is this https://developers.google.com/android-publisher/api-ref/rest/v3/monetization.subscriptions.basePlans.offers/get? I just need a normal subscription, and it still needs the offerId response, but there is no baseplan information I want.
<img width="1960" alt="image" src="https://github.com/googleapis/google-api-java-client/assets/58761705/4f9042e1-aff1-4bc3-9f43-cc6f3f3fad8b">

**Comment by JoeWang1127** [comment]
Hi @hakusai22, could you try our [Apiary client](https://github.com/googleapis/google-api-java-client-services/tree/main/clients/google-api-services-androidpublisher), rather than making REST calls directly?

**Comment by hakusai22** [comment]
@JoeWang1127 Thanks🙏

**Comment by JoeWang1127** [comment]
I'll close this issue and please reopen it if you have related questions.
