### ISSUE TITLE
GoogleJsonResponseException link to "Error Responses" is broken (404)

### ISSUE THREAD

**Issue by tivv** [googleapis/google-api-java-client#2513]
#### Code example

```java
/**
 * Exception thrown when an error status code is detected in an HTTP response to a Google API that
 * uses the JSON format, using the format specified in <a href=
 * "https://developers.google.com/url-shortener/v1/getting_started?csw=1#errors">Error
 * Responses</a>.
 */
```
from https://github.com/googleapis/google-api-java-client/blob/main/google-api-client/src/main/java/com/google/api/client/googleapis/json/GoogleJsonResponseException.java

#### External references such as API reference guides

The https://developers.google.com/url-shortener/v1/getting_started?csw=1#errors returns 404

**Comment by zhumin8** [comment]
Thanks for reporting. We will look into and have it fixed.
