### ISSUE TITLE
Google Play Android Developer API return 401

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-api-java-client#548]
_From [Jonhy.co...@gmail.com](https://code.google.com/u/107204799576606391748/) on June 20, 2012 00:58:05_

Version of google-api-java-client (e.g. 1.5.0-beta)? Google Play Android Developer API v1-rev2-1.7.1-beta Java environment (e.g. Java 6, Android 2.3, App Engine)? Java 6 Describe the problem. Server return 401 Unauthorized: This developer account does not own the application. How would you expect it to be fixed? HttpTransport HTTP_TRANSPORT = new NetHttpTransport();
                        JsonFactory JSON_FACTORY = new JacksonFactory();

```
                     GoogleCredential credential = new GoogleCredential.Builder().setTransport(HTTP_TRANSPORT)
                .setJsonFactory(JSON_FACTORY)
                .setServiceAccountId(GOOGLE_CLIENT_MAIL)
                .setServiceAccountScopes(" https://www.googleapis.com/auth/androidpublisher" )
                .setServiceAccountPrivateKeyFromP12File(new File(GOOGLE_KEY_FILE_PATH))
                .build();

        Androidpublisher publisher = new Androidpublisher.Builder(HTTP_TRANSPORT, JSON_FACTORY, credential).
                setApplicationName(GOOGLE_PRODUCT_NAME).
                build();

        Androidpublisher.Purchases purchases = publisher.purchases();
        Get get = purchases.get("XXXXX", subscriptionId, token);
        SubscriptionPurchase subscripcion = get.execute(); //LINE 1
```

In Google APIS Console the Service "Google Play Android Developer API" is enabled.
GOOGLE_CLIENT_MAIL is the email address from API Access from the Google Console.
GOOGLE_KEY_FILE_PATH is the p12 file downloaded from the API Access.
GOOGLE_PRODUCT_NAME is the product name from the branding information.

The code return in LINE 1:

```
"domain" : "androidpublisher",
"message" : "This developer account does not own the application.",
"reason" : "developerDoesNotOwnApplication"
```

_Original issue: http://code.google.com/p/google-api-java-client/issues/detail?id=533_

**Comment by manikantabandaru** [comment]
@wonderfly 
i am also facing same problem please tell me how you  solved above problem
The response from google play services 
{
  "code" : 401,
  "errors" : [ {
    "domain" : "androidpublisher",
    "message" : "The current user has insufficient permissions to perform the requested operation.",
    "reason" : "permissionDenied"
  } ],
  "message" : "The current user has insufficient permissions to perform the requested operation."
}

**Comment by wonderfly** [comment]
@manikantabandaru
Please note the "From xxx on YYYY" line on each comment. I used my own credentials to import these issues and comments from another issue tracker, but it doesn't mean I had anything to do with them. :)
