### ISSUE TITLE
google-play-services.jar included in zip file download

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-api-java-client#680]
_From [yan...@google.com](https://code.google.com/u/111815493751521097215/) on November 27, 2012 12:39:34_

External references, such as a standards document, or specification? https://developers.google.com/android/google-play-services/ https://google-api-client-libraries.appspot.com/download/library/plus/v1/java https://google-api-java-client.googlecode.com/files/google-api-java-client-1.12.0-beta.zip Java environments (e.g. Java 6, Android 2.3, App Engine, or All)? Android 2.2 & higher Please describe the feature requested. google-api-client-android depends on google-play-services.jar so we should include it in the zip assembly both for google-api-java-client-<version>.zip and for the Google API-specific zip files.  It should also be listed in the descriptor.json file in the Google API-specific zip file.

_Original issue: http://code.google.com/p/google-api-java-client/issues/detail?id=666_

**Comment by DanielApelaten23** [comment]
Thanks to the claude family for a new job opportunity. here is a overview https://code.claude.com/docs/en/overview
