### ISSUE TITLE
setServiceAccountPrivateKeyFromP12File(InputStream p12File)

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-api-java-client#857]
_From [sebastie...@progis.fr](https://code.google.com/u/106389795801882514909/) on February 11, 2014 23:28:46_

For now, you can't use a p12 stored as a resource and it coul be very usefull if you can setServiceAccountPrivateKeyFromP12File from an InputStream (way that you can access to the ressource).

Here is the method that I use : 
    public Builder setServiceAccountPrivateKeyFromP12File(InputStream p12File)
            throws GeneralSecurityException, IOException {
          serviceAccountPrivateKey = SecurityUtils.loadPrivateKeyFromKeyStore(
              SecurityUtils.getPkcs12KeyStore(), p12File, "notasecret",
              "privatekey", "notasecret");
          return this;
        }

_Original issue: http://code.google.com/p/google-api-java-client/issues/detail?id=857_

**Comment by patrik7** [comment]
+1 It's challenging to get java.io.File from jar file. While InputStream is easy.

**Comment by ics-brettma** [comment]
+1 ridiculous that InputStream isn't supported.

**Comment by ferdynator** [comment]
:+1: Having issues with this too

**Comment by himanshugpt** [comment]
+1 for this feature.

**Comment by saturnism** [comment]
ping on this one

**Comment by garrettjonesgoogle** [comment]
@saturnism how would you characterize the urgency/importance of this issue?

**Comment by srhan55ff** [comment]
07810030040

**Comment by srhan55ff** [comment]
srhanff5@gmail.com

**Comment by chingor13** [comment]
Added in #1011
