### ISSUE TITLE
Drive.file().get(key) fails with spreadsheet keys from google-apps-script

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-api-java-client#859]
_From [InstantW...@gmail.com](https://code.google.com/u/111576820561059654535/) on February 16, 2014 23:18:51_

Version of google-api-java-client (e.g. 1.15.0-rc)? v2-rev82-1.15.0-rc Java environment (e.g. Java 6, Android 2.3, App Engine)? App-Engine Describe the problem. Was working fine, then stopped working.

```
    Drive driveService = new Drive.Builder(TRANSPORT, JSON_FACTORY, credential).setApplicationName("CellMaster.com.au").build();
    File file = driveService.files().get(this.spreadsheetKey).execute();
```

Just noticed it now fails. I think it broke sometime in the last week or so. It fails with the execute(), it produces a 404 error. It gives the error when I use with the short spreadsheetKey that is produced by google apps script. The key produced by this google-apps-script code:

   SpreadsheetApp.getActiveSpreadsheet().getId();

But it works fine with a manual copy of the spreadsheet key from the url, such as https://docs.google.com/spreadsheet/ccc?key=0AkGlO9jJLGO8dHJrSE0wTEF2VXRSdGRlNVQaaVRad0E Note: the error is happening with old style spreadsheets, the 400,000 cell spreadsheets. I am not using the new style as they don't support GData yet. How would you expect it to be fixed? I don't want getting the key to be a manual process. So hopping you will make it work again. I suspect this stopped working in the last week, but the last time I am sure it worked was about be about 3 weeks ago.

_Original issue: http://code.google.com/p/google-api-java-client/issues/detail?id=859_

**Comment by drandreaskrueger** [comment]
I get a 

> Error
> You do not have permission to call getFileById (line ___).

**Comment by sduskis** [comment]
I'm closing this due to staleness.  Please open a new issue if this is still a problem.
