### ISSUE TITLE
Blogger API V3 Sample code (Java)

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-api-java-client#885]
_From [way2shop...@gmail.com](https://code.google.com/u/106604624999449942556/) on June 21, 2014 20:51:09_

Hi Google I need sample program to create new post using blogger v3 and app engine.

Thanks,
Annamalai.T

_Original issue: http://code.google.com/p/google-api-java-client/issues/detail?id=885_

**Comment by ryu1kn** [comment]
I was looking for a sample and didn't find it here; so I wrote one on my blog, in case anyone wants to have a look: https://blog.ryuichi.io/2020/04/use-blogger-api-from-its-java-client.html
