### ISSUE TITLE
YouTube Data API v3: Update of tags is send as comma separated string instead of list

### ISSUE THREAD

**Issue by SubshellDaniel** [googleapis/google-api-java-client#927]
Hi,

when we upload a video we set the "videos.snippet.tags". The Upload is done via "videos.insert" (`YouTube.videos().insert().execute()`). On changes to the metadata we call "videos.update" (`YouTube.videos().update().execute()`).

In the Java library the tags of `VideoSnippet` are of type `List<String>`. Therefore I would assume that the library would create a JSON list from this Java list. But as we can see in our YouTube-Channel (https://www.youtube.com/edit?o=U&video_id=<videoid>), after updating the video the list of single tags are changed to a single long tag with comma separated words.

To further analyze this problem, I enabled the logging for `HttpTransport` to take a look at the transferred JSON. To my astonishment the update request contained only a single string in the JSON list:

```
"tags":["tag1, tag2, tag3"]
```

Even more astonishing is, that beside that the website shows exactly this tag, the API returns a list with the separated words in it's response. Also further "videos.list" request deliver a list with separate tags.

This is very confusing. I don't understand why the insert and update request differ, although the same Java object is used. It would be great if this can be fixed.

Thanks
Daniel

**Comment by SubshellDaniel** [comment]
The only difference in calling the library is how the `Video` object is created:
- Upload: `new Video()`
- Update: `YouTube.videos().list().setId().execute().getItems().get(0)`

**Comment by ajaaym** [comment]
Can you please try with latest version and reopen this issue if its not resolved?

**Comment by SubshellDaniel** [comment]
We got the same result with the latest release on Maven Central: v3-rev20190128-1.28.0

**Comment by sduskis** [comment]
@ajaaym, can you please get someone to look at this?

**Comment by ajaaym** [comment]
@sduskis yeah its in progress.

**Comment by chingor13** [comment]
This may have been a server side bug, but seems to work fine now. The video tags are correct when I tested both insert and update. Note: I am using `google-api-services-youtube` version `v3-rev20190827-1.30.1`

Insert:
```java
Video video = new Video()
    .setSnippet(
        new VideoSnippet()
            .setTags(ImmutableList.of("foo", "bar")));
File mediaFile = new File(TEST_FILE);
InputStreamContent mediaContent =
    new InputStreamContent("video/*",
        new BufferedInputStream(new FileInputStream(mediaFile)));
mediaContent.setLength(mediaFile.length());

YouTube.Videos.Insert request = youtubeService.videos()
    .insert("snippet", video, mediaContent);
Video response = request.execute();
```

Update:
```java
YouTube.Videos.List request = youtubeService.videos().list("snippet")
    .setId("VIDEO_ID");
video.setSnippet(video.getSnippet().setTags(ImmutableList.of("foo", "bar")));
YouTube.Videos.Update request = youtubeService.videos().update("snippet", video);
Video response = request.execute();
```

List:
```java
// list the tags (might take a bit to propagate)
YouTube.Videos.List request = youtubeService.videos().list("snippet")
    .setId("VIDEO_ID");
VideoListResponse response = request.execute();
Video video = response.getItems().get(0);
System.out.println(video.getSnippet().getTags());
```
