### ISSUE TITLE
Execute should have an optional "retries" flag

### ISSUE THREAD

**Issue by elibixby** [googleapis/google-api-java-client#930]
This prevents users form having to implement best error handling practices (exponential backoff/fuzzing) and eliminates a lot of boilerplate code. 

Also would be in line with other client libraries (python for example)

**Comment by elibixby** [comment]
#931

**Comment by nddipiazza** [comment]
:+1:

**Comment by chingor13** [comment]
Retries are already available and can be configured by your request factory.
