### ISSUE TITLE
Replace GoogleAuthUtil.invalidateToken with GoogleAuthUtil.clearToken

### ISSUE THREAD

**Issue by erickoledadevrel** [googleapis/google-api-java-client#950]
It's used here:

https://github.com/google/google-api-java-client/blob/57fe35766cbba0a0d5a9a296be81468d730a29f8/google-api-client-android/src/main/java/com/google/api/client/googleapis/extensions/android/gms/auth/GoogleAccountCredential.java#L294

The method is deprecated due to requiring MANAGE_ACCOUNTS and USE_CREDENTIALS permissions:

https://developers.google.com/android/reference/com/google/android/gms/auth/GoogleAuthUtil#invalidateToken(android.content.Context, java.lang.String)

The replacement is GoogleAuthUtil.clearToken. This should allow Android developers to use the library without requesting those extra permissions.

**Comment by devconsole** [comment]
Also GoogleAccountCredential.setSelectedAccountName() requires GET_ACCOUNTS. It should delegate this work to Play Services instead. com.google.android.gms.common.api.GoogleApiClient does not require any account-related permissions and in my opinion neither should GoogleAccountCredential.
